# Generated by hand for the task-43 protected-field integration on 2026-09-22
"""Encrypt patient identity, contact destinations and questionnaire payloads.

``intake_patient.full_name``/``birth_date``, ``intake_patientcontact``.
``destination``, ``intake_questionnaireresponse.answers``/``reopen_reason``
and ``intake_questionnaireevent.answers`` become tenant-envelope ``bytea``
columns. The plaintext copies are renamed to ``*_legacy``, backfilled through
``clinic_app.protected_encrypt`` one table per transaction with an
in-database decrypt-and-compare check, then dropped. Every database
operation is idempotent so an interrupted run resumes; the migration is
irreversible because rollback must never reactivate plaintext storage.

The patient overview resolver is recreated in the same migration: it now
takes the KEK and decrypts ``full_name`` through ``protected_decrypt``
inside the session-validating boundary, so the patient home screen keeps
showing the patient's name instead of ciphertext.

The questionnaire guard is recreated for the new column types: an initial
response must carry no envelope, and a reopened response must carry a
non-NULL reopen-reason envelope.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING, ClassVar

import rfc8785
from django.db import migrations

import apps.tenancy.fields
from apps.tenancy.migrations._protected_migration import (
    drop_constraint_sql,
    drop_legacy_sql,
    encrypt_backfill,
    irreversible,
    rename_to_legacy_sql,
    require_backfill_complete,
)

if TYPE_CHECKING:
    from typing import Any

    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.operations.base import Operation


def _encode_text(value: object) -> bytes | None:
    if value is None or value == "":
        return None
    return str(value).encode("utf-8")


def _encode_json(value: object) -> bytes | None:
    """Encode one legacy JSONB value as the field's canonical-JSON envelope.

    The raw migration cursor returns JSONB as its text representation, so a
    ``str`` is parsed back to the logical value before canonicalization —
    the stored plaintext must be the JSON document, never a JSON string
    containing one.
    """
    if value is None:
        return None
    parsed: Any = json.loads(value) if isinstance(value, str) else value
    return rfc8785.dumps(parsed)


_PATIENT_PLANS = (
    (
        "full_name",
        "intake.patient.full_name",
        ("full_name_legacy",),
        (),
        lambda row: _encode_text(row["full_name_legacy"]),
        None,
    ),
    (
        "birth_date",
        "intake.patient.birth_date",
        ("birth_date_legacy",),
        (),
        lambda row: (
            None
            if row["birth_date_legacy"] is None
            else row["birth_date_legacy"].isoformat().encode("ascii")
        ),
        None,
    ),
)
_CONTACT_PLANS = (
    (
        "destination",
        "intake.patientcontact.destination",
        ("destination_legacy",),
        (),
        lambda row: _encode_text(row["destination_legacy"]),
        None,
    ),
)
_RESPONSE_PLANS = (
    (
        "answers",
        "intake.questionnaireresponse.answers",
        ("answers_legacy",),
        (),
        lambda row: _encode_json(row["answers_legacy"]),
        None,
    ),
    (
        "reopen_reason",
        "intake.questionnaireresponse.reopen_reason",
        ("reopen_reason_legacy",),
        (),
        lambda row: _encode_text(row["reopen_reason_legacy"]),
        None,
    ),
)
_EVENT_PLANS = (
    (
        "answers",
        "intake.questionnaireresponse.answers",
        ("answers_legacy",),
        (),
        lambda row: _encode_json(row["answers_legacy"]),
        None,
    ),
    (
        "reason",
        "intake.questionnaireresponse.reopen_reason",
        ("reason_legacy",),
        (),
        lambda row: _encode_text(row["reason_legacy"]),
        None,
    ),
)

_SCHEMA_SQL = (
    rename_to_legacy_sql("intake_patient", "full_name")
    + rename_to_legacy_sql("intake_patient", "birth_date")
    + rename_to_legacy_sql("intake_patientcontact", "destination")
    + rename_to_legacy_sql("intake_questionnaireresponse", "answers")
    + rename_to_legacy_sql("intake_questionnaireresponse", "reopen_reason")
    + rename_to_legacy_sql("intake_questionnaireevent", "answers")
    + rename_to_legacy_sql("intake_questionnaireevent", "reason")
    + drop_constraint_sql("intake_patient", "intake_patient_full_name_normalized_check")
    + """
-- Column-level UPDATE grants follow the renamed legacy columns; the new
-- envelope columns need their own grants for the runtime write paths.
GRANT UPDATE (destination) ON clinic_app.intake_patientcontact TO clinic_app;
GRANT UPDATE (answers, reopen_reason)
    ON clinic_app.intake_questionnaireresponse TO clinic_app;
"""
)

_OVERVIEW_SQL = """
-- The resolver decrypts inside its own boundary exactly like the
-- prescription document resolvers: the KEK arrives per call from the
-- application secret store, and protected_decrypt resolves the tenant from
-- the live patient session row it re-validates.
GRANT EXECUTE ON FUNCTION clinic_app.protected_decrypt(
  pg_catalog.text, pg_catalog.text, pg_catalog.bytea) TO clinic_resolver;
SET LOCAL ROLE clinic_resolver;
DROP FUNCTION IF EXISTS clinic_app.patient_session_overview();
CREATE FUNCTION clinic_app.patient_session_overview(
    kek pg_catalog.text
)
RETURNS TABLE(
    session_id pg_catalog.uuid,
    patient_name pg_catalog.varchar,
    clinic_name pg_catalog.varchar,
    enrolled_at pg_catalog.timestamptz,
    operations pg_catalog.text[],
    expires_at pg_catalog.timestamptz,
    idle_expires_at pg_catalog.timestamptz
)
LANGUAGE sql
STABLE
PARALLEL UNSAFE
SECURITY DEFINER
ROWS 1
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
    SELECT session_row.id,
           CASE WHEN patient.full_name IS NULL THEN NULL
                ELSE pg_catalog.convert_from(
                    clinic_app.protected_decrypt(
                        kek, 'intake.patient.full_name', patient.full_name
                    ),
                    'UTF8'
                )
           END,
           clinic.name,
           enrollment.created_at,
           session_row.operations::pg_catalog.text[],
           session_row.expires_at,
           session_row.idle_expires_at
    FROM clinic_app.intake_patientsession AS session_row
    JOIN clinic_app.intake_patientaccessgrant AS grant_row
      ON grant_row.id = session_row.grant_id
     AND grant_row.revoked_at IS NULL
    JOIN clinic_app.intake_patient AS patient
      ON patient.organization_id = session_row.organization_id
     AND patient.id = session_row.patient_id
    JOIN clinic_app.identity_clinic AS clinic
      ON clinic.organization_id = session_row.organization_id
     AND clinic.id = session_row.clinic_id
    JOIN clinic_app.intake_patientclinicenrollment AS enrollment
      ON enrollment.organization_id = session_row.organization_id
     AND enrollment.clinic_id = session_row.clinic_id
     AND enrollment.id = session_row.enrollment_id
    WHERE session_row.id = NULLIF(
        pg_catalog.current_setting('app.current_patient_session', true),
        ''
    )::pg_catalog.uuid
      AND session_row.revoked_at IS NULL
      AND session_row.expires_at > pg_catalog.now()
      AND session_row.idle_expires_at > pg_catalog.now()
$function$;
REVOKE ALL PRIVILEGES
    ON FUNCTION clinic_app.patient_session_overview(pg_catalog.text)
    FROM PUBLIC;
GRANT EXECUTE
    ON FUNCTION clinic_app.patient_session_overview(pg_catalog.text)
    TO clinic_app;
RESET ROLE;
"""

_GUARD_SQL = """
SET LOCAL ROLE clinic_resolver;
CREATE OR REPLACE FUNCTION clinic_app.questionnaire_response_guard()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp AS $f$
BEGIN
 IF NOT EXISTS (
    SELECT 1 FROM clinic_app.intake_patientclinicenrollment e
    JOIN clinic_app.intake_questionnairetemplate t ON t.id = NEW.template_id
    WHERE e.id = NEW.enrollment_id AND e.patient_id = NEW.patient_id
      AND e.clinic_id = NEW.clinic_id AND e.organization_id = NEW.organization_id
      AND t.clinic_id = NEW.clinic_id AND t.organization_id = NEW.organization_id
 ) OR (NEW.appointment_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM clinic_app.scheduling_appointment a
    WHERE a.id = NEW.appointment_id AND a.patient_id = NEW.patient_id
      AND a.clinic_id = NEW.clinic_id AND a.organization_id = NEW.organization_id
 )) THEN
    RAISE EXCEPTION 'invalid questionnaire binding' USING ERRCODE = '23514';
 END IF;
 IF TG_OP = 'INSERT' THEN
    IF NEW.state <> 'draft' OR NEW.revision <> 1 OR NEW.answers IS NOT NULL THEN
      RAISE EXCEPTION 'invalid initial response' USING ERRCODE = '23514';
    END IF;
 ELSE
    IF (NEW.organization_id, NEW.clinic_id, NEW.patient_id, NEW.enrollment_id,
        NEW.template_id, NEW.appointment_id, NEW.created_at)
       IS DISTINCT FROM
       (OLD.organization_id, OLD.clinic_id, OLD.patient_id, OLD.enrollment_id,
        OLD.template_id, OLD.appointment_id, OLD.created_at)
       OR NEW.revision <> OLD.revision + 1 THEN
      RAISE EXCEPTION 'immutable binding or stale revision' USING ERRCODE = '23514';
    END IF;
    IF OLD.state = 'submitted' THEN
      IF NEW.state <> 'draft' OR NEW.answers IS DISTINCT FROM OLD.answers
         OR NEW.reopen_reason IS NULL
         OR NOT clinic_app.questionnaire_staff(NEW.clinic_id, ARRAY['physician']) THEN
        RAISE EXCEPTION 'clinical reopening required' USING ERRCODE = '23514';
      END IF;
    ELSIF NEW.enrollment_id IS DISTINCT FROM
          clinic_app.questionnaire_patient_enrollment()
       OR NEW.reopen_reason IS DISTINCT FROM OLD.reopen_reason THEN
      RAISE EXCEPTION 'patient session required' USING ERRCODE = '23514';
    END IF;
 END IF;
 RETURN NEW;
END
$f$;
"""

_DROP_SQL = (
    drop_legacy_sql("intake_patient", "full_name", required=True)
    + drop_legacy_sql("intake_patient", "birth_date", required=True)
    + drop_legacy_sql("intake_patientcontact", "destination", required=True)
    + drop_legacy_sql("intake_questionnaireresponse", "answers", required=False)
    + drop_legacy_sql("intake_questionnaireresponse", "reopen_reason", required=False)
    + drop_legacy_sql("intake_questionnaireevent", "answers", required=False)
    + drop_legacy_sql("intake_questionnaireevent", "reason", required=False)
    + """
ALTER TABLE clinic_app.intake_patient
    ALTER COLUMN full_name SET NOT NULL,
    ALTER COLUMN birth_date SET NOT NULL;
ALTER TABLE clinic_app.intake_patientcontact
    ALTER COLUMN destination SET NOT NULL;
"""
)


def _backfill(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    encrypt_backfill(table="intake_patient", pk_column="id", plans=_PATIENT_PLANS)(
        apps, schema_editor
    )
    encrypt_backfill(
        table="intake_patientcontact", pk_column="id", plans=_CONTACT_PLANS
    )(apps, schema_editor)
    encrypt_backfill(
        table="intake_questionnaireresponse",
        pk_column="id",
        plans=_RESPONSE_PLANS,
    )(apps, schema_editor)
    encrypt_backfill(
        table="intake_questionnaireevent", pk_column="id", plans=_EVENT_PLANS
    )(apps, schema_editor)


def _seal(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    for table, plans in (
        ("intake_patient", _PATIENT_PLANS),
        ("intake_patientcontact", _CONTACT_PLANS),
        ("intake_questionnaireresponse", _RESPONSE_PLANS),
        ("intake_questionnaireevent", _EVENT_PLANS),
    ):
        require_backfill_complete(table=table, plans=plans)(apps, schema_editor)


class Migration(migrations.Migration):
    """Convert intake protected columns to tenant envelopes."""

    atomic = False
    dependencies: ClassVar[list[tuple[str, str]]] = [
        (
            "intake",
            "0010_remove_patientaccessgrant_intake_grant_operations_check_and_more",
        ),
        ("tenancy", "0004_protected_fields"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_SCHEMA_SQL, reverse_sql=None),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name="patient",
                    old_name="full_name",
                    new_name="full_name_legacy",
                ),
                migrations.RenameField(
                    model_name="patient",
                    old_name="birth_date",
                    new_name="birth_date_legacy",
                ),
                migrations.RenameField(
                    model_name="patientcontact",
                    old_name="destination",
                    new_name="destination_legacy",
                ),
                migrations.RenameField(
                    model_name="questionnaireresponse",
                    old_name="answers",
                    new_name="answers_legacy",
                ),
                migrations.RenameField(
                    model_name="questionnaireresponse",
                    old_name="reopen_reason",
                    new_name="reopen_reason_legacy",
                ),
                migrations.RenameField(
                    model_name="questionnaireevent",
                    old_name="answers",
                    new_name="answers_legacy",
                ),
                migrations.RenameField(
                    model_name="questionnaireevent",
                    old_name="reason",
                    new_name="reason_legacy",
                ),
                migrations.AddField(
                    model_name="patient",
                    name="full_name",
                    field=apps.tenancy.fields.EncryptedPatientNameField(
                        purpose="intake.patient.full_name", null=True
                    ),
                ),
                migrations.AddField(
                    model_name="patient",
                    name="birth_date",
                    field=apps.tenancy.fields.EncryptedDateField(
                        purpose="intake.patient.birth_date", null=True
                    ),
                ),
                migrations.AddField(
                    model_name="patientcontact",
                    name="destination",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="intake.patientcontact.destination", null=True
                    ),
                ),
                migrations.AddField(
                    model_name="questionnaireresponse",
                    name="answers",
                    field=apps.tenancy.fields.EncryptedJSONField(
                        purpose="intake.questionnaireresponse.answers",
                        null=True,
                        empty={},
                    ),
                ),
                migrations.AddField(
                    model_name="questionnaireresponse",
                    name="reopen_reason",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="intake.questionnaireresponse.reopen_reason",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="questionnaireevent",
                    name="answers",
                    field=apps.tenancy.fields.EncryptedJSONField(
                        purpose="intake.questionnaireresponse.answers",
                        null=True,
                        empty={},
                    ),
                ),
                migrations.AddField(
                    model_name="questionnaireevent",
                    name="reason",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="intake.questionnaireresponse.reopen_reason",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RunPython(code=_backfill, reverse_code=irreversible),
        migrations.RunSQL(sql=_GUARD_SQL, reverse_sql=None),
        migrations.RunSQL(sql=_OVERVIEW_SQL, reverse_sql=None),
        migrations.RunPython(code=_seal, reverse_code=irreversible),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_DROP_SQL, reverse_sql=None),
            ],
            state_operations=[
                migrations.RemoveField(model_name="patient", name="full_name_legacy"),
                migrations.RemoveField(model_name="patient", name="birth_date_legacy"),
                migrations.RemoveField(
                    model_name="patientcontact", name="destination_legacy"
                ),
                migrations.RemoveField(
                    model_name="questionnaireresponse", name="answers_legacy"
                ),
                migrations.RemoveField(
                    model_name="questionnaireresponse",
                    name="reopen_reason_legacy",
                ),
                migrations.RemoveField(
                    model_name="questionnaireevent", name="answers_legacy"
                ),
                migrations.RemoveField(
                    model_name="questionnaireevent", name="reason_legacy"
                ),
                migrations.AlterField(
                    model_name="patient",
                    name="full_name",
                    field=apps.tenancy.fields.EncryptedPatientNameField(
                        purpose="intake.patient.full_name"
                    ),
                ),
                migrations.AlterField(
                    model_name="patient",
                    name="birth_date",
                    field=apps.tenancy.fields.EncryptedDateField(
                        purpose="intake.patient.birth_date"
                    ),
                ),
                migrations.AlterField(
                    model_name="patientcontact",
                    name="destination",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="intake.patientcontact.destination"
                    ),
                ),
            ],
        ),
    ]
