# Generated by hand for todo 17 patient identity expansion on 2026-09-25
# ruff: noqa: S608, E501 - DDL built from migration literals; generated model ops
"""Add versioned demographics, identifiers, contacts and correction history.

Seven intake tables ship already-encrypted columns, composite
organization-scoped foreign keys, FORCE RLS through the shared
``tenant_isolation`` helper and a REVOKE down to SELECT/INSERT for the
runtime role. Every identity table is append-only history: a correction
inserts the next dense ``version`` and nothing is ever rewritten or hard
deleted - BEFORE UPDATE/DELETE triggers refuse it for every role, including
the owner (the runtime role holds no TRUNCATE privilege). Version and
receipt transitions are enforced in the database: each table accepts only
the next version of its key, a retirement only on an active version, a
demographics version only with its correction receipt (deferred to commit)
and a receipt only when it names the version it superseded. ``intake_patient.full_name``/``birth_date`` mirror the latest
demographics version; the runtime role may update exactly those columns,
only inside the transaction that appended that version and only to the
exact envelope bytes that version recorded for the registry.

Identifier exact search runs on a tenant-keyed HMAC blind index computed
inside the database boundary by ``clinic_app.protected_blind_index``
(clinic_owner-owned SECURITY DEFINER, mirroring ``protected_encrypt``). The
registry search functions fold diacritics and case over legal and social
names, and the patient-session overview prefers the social name.

Protected-field migration contract (SC-5/SC-17, H-10): the migration is
non-atomic and irreversible - every SQL step runs in its own transaction and
unapply raises before touching the database, because unapplying would drop
protected identity history. Rollback = restore on the owned restored target
(``make restore-rehearsal``).
"""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING, ClassVar

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import connection, migrations, models, transaction

import apps.tenancy.fields
from apps.intake.rls import apply_intake_rls

if TYPE_CHECKING:
    from collections.abc import Callable

    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.operations.base import Operation

NEW_RLS_TABLES = (
    "intake_patientdemographics",
    "intake_demographicscorrection",
    "intake_patientidentifier",
    "intake_patientaddress",
    "intake_emergencycontact",
    "intake_insurancemembership",
    "intake_clinicintakepolicy",
)

_EXTENSION_SQL = """
DO $guard$
DECLARE
    installed_schema pg_catalog.text;
BEGIN
    SELECT namespace.nspname
      INTO installed_schema
      FROM pg_catalog.pg_extension AS extension
      JOIN pg_catalog.pg_namespace AS namespace
        ON namespace.oid = extension.extnamespace
     WHERE extension.extname = 'unaccent';

    IF installed_schema IS NOT NULL AND installed_schema <> 'clinic_app' THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'unaccent must be installed in clinic_app schema';
    END IF;
END
$guard$;

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA clinic_app;
"""

_INTEGRITY_SQL = """
ALTER TABLE clinic_app.intake_patientdemographics
    ADD CONSTRAINT intake_demographics_org_patient_fk
    FOREIGN KEY (organization_id, patient_id)
    REFERENCES clinic_app.intake_patient (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_patientdemographics
    ADD CONSTRAINT intake_demographics_org_clinic_fk
    FOREIGN KEY (organization_id, clinic_id)
    REFERENCES clinic_app.identity_clinic (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_patientdemographics
    ADD CONSTRAINT intake_demographics_org_enrollment_fk
    FOREIGN KEY (organization_id, clinic_id, enrollment_id)
    REFERENCES clinic_app.intake_patientclinicenrollment
        (organization_id, clinic_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_demographicscorrection
    ADD CONSTRAINT intake_correction_org_patient_fk
    FOREIGN KEY (organization_id, patient_id)
    REFERENCES clinic_app.intake_patient (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_demographicscorrection
    ADD CONSTRAINT intake_correction_org_clinic_fk
    FOREIGN KEY (organization_id, clinic_id)
    REFERENCES clinic_app.identity_clinic (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_demographicscorrection
    ADD CONSTRAINT intake_correction_org_demographics_fk
    FOREIGN KEY (organization_id, demographics_id)
    REFERENCES clinic_app.intake_patientdemographics (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_demographicscorrection
    ADD CONSTRAINT intake_correction_org_previous_fk
    FOREIGN KEY (organization_id, previous_id)
    REFERENCES clinic_app.intake_patientdemographics (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_patientidentifier
    ADD CONSTRAINT intake_identifier_org_patient_fk
    FOREIGN KEY (organization_id, patient_id)
    REFERENCES clinic_app.intake_patient (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_patientidentifier
    ADD CONSTRAINT intake_identifier_org_clinic_fk
    FOREIGN KEY (organization_id, clinic_id)
    REFERENCES clinic_app.identity_clinic (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_patientaddress
    ADD CONSTRAINT intake_address_org_patient_fk
    FOREIGN KEY (organization_id, patient_id)
    REFERENCES clinic_app.intake_patient (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_emergencycontact
    ADD CONSTRAINT intake_emergency_contact_org_patient_fk
    FOREIGN KEY (organization_id, patient_id)
    REFERENCES clinic_app.intake_patient (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_insurancemembership
    ADD CONSTRAINT intake_membership_org_patient_fk
    FOREIGN KEY (organization_id, patient_id)
    REFERENCES clinic_app.intake_patient (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_clinicintakepolicy
    ADD CONSTRAINT intake_policy_org_clinic_fk
    FOREIGN KEY (organization_id, clinic_id)
    REFERENCES clinic_app.identity_clinic (organization_id, id)
    NOT DEFERRABLE;
"""

_APPEND_ONLY_SQL = """
CREATE OR REPLACE FUNCTION clinic_app.intake_identity_append_only_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, clinic_app
AS $function$
BEGIN
    RAISE EXCEPTION USING
        ERRCODE = '23514',
        CONSTRAINT = 'intake_identity_append_only_check',
        MESSAGE = 'patient identity history is append-only';
END;
$function$;
REVOKE ALL ON FUNCTION clinic_app.intake_identity_append_only_v1()
    FROM PUBLIC, clinic_app, clinic_resolver;
""" + "".join(
    f"""
DROP TRIGGER IF EXISTS {table}_append_only ON clinic_app.{table};
CREATE TRIGGER {table}_append_only
BEFORE UPDATE OR DELETE ON clinic_app.{table}
FOR EACH ROW EXECUTE FUNCTION clinic_app.intake_identity_append_only_v1();
"""
    for table in NEW_RLS_TABLES
)

# (table, key columns, retirable, stamps created_at): each insert must be the
# next dense version of its key; a retirement must follow an active version.
_VERSIONED_TABLES: tuple[tuple[str, tuple[str, ...], bool, bool], ...] = (
    ("intake_patientdemographics", ("organization_id", "patient_id"), False, True),
    (
        "intake_patientidentifier",
        ("organization_id", "patient_id", "kind"),
        True,
        False,
    ),
    ("intake_patientaddress", ("organization_id", "patient_id", "kind"), True, False),
    (
        "intake_emergencycontact",
        ("organization_id", "patient_id", "sequence"),
        True,
        False,
    ),
    (
        "intake_insurancemembership",
        ("organization_id", "patient_id", "sequence"),
        True,
        False,
    ),
    ("intake_clinicintakepolicy", ("organization_id", "clinic_id"), False, False),
)


def _version_guard_sql(
    table: str, keys: tuple[str, ...], retirable: bool, stamps: bool
) -> str:
    match = " AND ".join(f"latest_row.{key} = NEW.{key}" for key in keys)
    retire = (
        """
    IF NEW.retired_at IS NOT NULL
        AND (latest_version = 0 OR latest_retired IS NOT NULL)
    THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            CONSTRAINT = 'intake_identity_version_check',
            MESSAGE = 'only an active identity version can be retired';
    END IF;"""
        if retirable
        else ""
    )
    select_retired = ", latest_row.retired_at" if retirable else ""
    into_retired = ", latest_retired" if retirable else ""
    declare_retired = (
        "\n    latest_retired pg_catalog.timestamptz;" if retirable else ""
    )
    stamp = (
        "\n    NEW.created_at := pg_catalog.transaction_timestamp();" if stamps else ""
    )
    return f"""
CREATE OR REPLACE FUNCTION clinic_app.{table}_version_guard_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, clinic_app
AS $function$
DECLARE
    latest_version pg_catalog.int8 := 0;{declare_retired}
BEGIN
    SELECT latest_row.version{select_retired}
      INTO latest_version{into_retired}
      FROM clinic_app.{table} AS latest_row
     WHERE {match}
     ORDER BY latest_row.version DESC
     LIMIT 1;
    latest_version := COALESCE(latest_version, 0);
    IF NEW.version IS DISTINCT FROM latest_version + 1 THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            CONSTRAINT = 'intake_identity_version_check',
            MESSAGE = 'identity versions must follow the latest version';
    END IF;{retire}{stamp}
    RETURN NEW;
END;
$function$;
REVOKE ALL ON FUNCTION clinic_app.{table}_version_guard_v1()
    FROM PUBLIC, clinic_app, clinic_resolver;
DROP TRIGGER IF EXISTS {table}_version_guard ON clinic_app.{table};
CREATE TRIGGER {table}_version_guard
BEFORE INSERT ON clinic_app.{table}
FOR EACH ROW EXECUTE FUNCTION clinic_app.{table}_version_guard_v1();
"""


_VERSION_GUARD_SQL = "".join(
    _version_guard_sql(table, keys, retirable, stamps)
    for table, keys, retirable, stamps in _VERSIONED_TABLES
)

_RECEIPT_GUARD_SQL = """
-- A receipt binds exactly the version it produced and names the version that
-- version superseded; the first version supersedes nothing.
CREATE OR REPLACE FUNCTION clinic_app.intake_correction_guard_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, clinic_app
AS $function$
DECLARE
    produced_patient pg_catalog.uuid;
    produced_clinic pg_catalog.uuid;
    produced_version pg_catalog.int8;
    superseded pg_catalog.uuid;
BEGIN
    SELECT produced_row.patient_id, produced_row.clinic_id, produced_row.version
      INTO produced_patient, produced_clinic, produced_version
      FROM clinic_app.intake_patientdemographics AS produced_row
     WHERE produced_row.organization_id = NEW.organization_id
       AND produced_row.id = NEW.demographics_id;
    IF produced_version IS NULL
        OR produced_patient IS DISTINCT FROM NEW.patient_id
        OR produced_clinic IS DISTINCT FROM NEW.clinic_id
    THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            CONSTRAINT = 'intake_correction_binding_check',
            MESSAGE = 'a correction receipt must bind its own version';
    END IF;
    SELECT previous_row.id INTO superseded
      FROM clinic_app.intake_patientdemographics AS previous_row
     WHERE previous_row.organization_id = NEW.organization_id
       AND previous_row.patient_id = NEW.patient_id
       AND previous_row.version = produced_version - 1;
    IF NEW.previous_id IS DISTINCT FROM superseded THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            CONSTRAINT = 'intake_correction_binding_check',
            MESSAGE = 'a correction receipt must name the superseded version';
    END IF;
    NEW.created_at := pg_catalog.transaction_timestamp();
    RETURN NEW;
END;
$function$;
REVOKE ALL ON FUNCTION clinic_app.intake_correction_guard_v1()
    FROM PUBLIC, clinic_app, clinic_resolver;
DROP TRIGGER IF EXISTS intake_correction_guard
    ON clinic_app.intake_demographicscorrection;
CREATE TRIGGER intake_correction_guard
BEFORE INSERT ON clinic_app.intake_demographicscorrection
FOR EACH ROW EXECUTE FUNCTION clinic_app.intake_correction_guard_v1();

-- Every demographics version must carry its correction receipt by commit.
CREATE OR REPLACE FUNCTION clinic_app.intake_demographics_receipt_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, clinic_app
AS $function$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM clinic_app.intake_demographicscorrection AS receipt_row
         WHERE receipt_row.organization_id = NEW.organization_id
           AND receipt_row.demographics_id = NEW.id
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            CONSTRAINT = 'intake_demographics_receipt_check',
            MESSAGE = 'every demographics version needs its correction receipt';
    END IF;
    RETURN NULL;
END;
$function$;
REVOKE ALL ON FUNCTION clinic_app.intake_demographics_receipt_v1()
    FROM PUBLIC, clinic_app, clinic_resolver;
DROP TRIGGER IF EXISTS intake_demographics_receipt
    ON clinic_app.intake_patientdemographics;
CREATE CONSTRAINT TRIGGER intake_demographics_receipt
AFTER INSERT ON clinic_app.intake_patientdemographics
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION clinic_app.intake_demographics_receipt_v1();

-- The registry row mirrors the latest demographics version: its identity
-- binding never changes, and its name/date change only in the transaction
-- that appended that version (the version stamps transaction_timestamp())
-- and only to the exact envelopes that version recorded for the registry.
CREATE OR REPLACE FUNCTION clinic_app.intake_patient_mirror_guard_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, clinic_app
AS $function$
DECLARE
    latest_name pg_catalog.bytea;
    latest_birth pg_catalog.bytea;
    latest_at pg_catalog.timestamptz;
BEGIN
    IF (NEW.id, NEW.organization_id, NEW.created_at)
        IS DISTINCT FROM (OLD.id, OLD.organization_id, OLD.created_at)
    THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            CONSTRAINT = 'intake_patient_mirror_check',
            MESSAGE = 'patient identity binding is immutable';
    END IF;
    SELECT version_row.registry_full_name, version_row.registry_birth_date,
           version_row.created_at
      INTO latest_name, latest_birth, latest_at
      FROM clinic_app.intake_patientdemographics AS version_row
     WHERE version_row.organization_id = NEW.organization_id
       AND version_row.patient_id = NEW.id
     ORDER BY version_row.version DESC
     LIMIT 1;
    IF latest_at IS DISTINCT FROM pg_catalog.transaction_timestamp() THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            CONSTRAINT = 'intake_patient_mirror_check',
            MESSAGE = 'patient registry identity changes only with a demographics version';
    END IF;
    IF NEW.full_name IS DISTINCT FROM latest_name
        OR NEW.birth_date IS DISTINCT FROM latest_birth
    THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            CONSTRAINT = 'intake_patient_mirror_check',
            MESSAGE = 'patient registry identity must equal the latest demographics version';
    END IF;
    RETURN NEW;
END;
$function$;
REVOKE ALL ON FUNCTION clinic_app.intake_patient_mirror_guard_v1()
    FROM PUBLIC, clinic_app, clinic_resolver;
DROP TRIGGER IF EXISTS intake_patient_mirror_guard ON clinic_app.intake_patient;
CREATE TRIGGER intake_patient_mirror_guard
BEFORE UPDATE ON clinic_app.intake_patient
FOR EACH ROW EXECUTE FUNCTION clinic_app.intake_patient_mirror_guard_v1();
"""

_BLIND_INDEX_SQL = """
-- Tenant-keyed HMAC for exact-match identifier lookup. The DEK is unwrapped
-- per version inside the boundary so a lookup issued after a key rotation
-- still answers for rows indexed under retired versions; the caller picks
-- the highest-version digest for writes and tries every digest for reads.
-- The tenant resolves through protected_tenant(), so staff contexts set
-- app.current_tenant for the inner unwrap exactly like protected_encrypt.
CREATE FUNCTION clinic_app.protected_blind_index(
    kek pg_catalog.text,
    purpose pg_catalog.text,
    plaintext pg_catalog.bytea
)
RETURNS TABLE(
    blind_index pg_catalog.bytea,
    key_version pg_catalog.int4
)
LANGUAGE plpgsql
VOLATILE
PARALLEL UNSAFE
SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
DECLARE
    prior_tenant pg_catalog.text;
    resolved pg_catalog.uuid;
    key_row pg_catalog.record;
BEGIN
    resolved := clinic_app.protected_tenant();
    prior_tenant := pg_catalog.current_setting('app.current_tenant', true);
    PERFORM pg_catalog.set_config(
        'app.current_tenant', resolved::pg_catalog.text, true
    );
    IF kek IS NULL OR NOT kek ~ '^[0-9a-f]{64}$' THEN
        RAISE EXCEPTION USING ERRCODE = '22023',
            MESSAGE = 'wrapping key must be 32 bytes hex-encoded';
    END IF;
    IF purpose IS NULL
        OR pg_catalog.char_length(purpose) NOT BETWEEN 1 AND 128
        OR purpose ~ '[[:cntrl:]]'
    THEN
        RAISE EXCEPTION USING ERRCODE = '22023',
            MESSAGE = 'envelope purpose must be 1-128 printable characters';
    END IF;
    IF plaintext IS NULL THEN
        RAISE EXCEPTION USING ERRCODE = '22023',
            MESSAGE = 'envelope plaintext is required';
    END IF;
    FOR key_row IN
        SELECT version_row.key_version
          FROM clinic_app.tenancy_tenantdatakey AS version_row
         WHERE version_row.organization_id = resolved
         ORDER BY version_row.key_version
    LOOP
        blind_index := clinic_app.hmac(
            pg_catalog.convert_to(purpose, 'UTF8')
                || pg_catalog.decode('00', 'hex')
                || plaintext,
            clinic_app.tenant_dek_unwrap(kek, key_row.key_version),
            'sha256'
        );
        key_version := key_row.key_version;
        RETURN NEXT;
    END LOOP;
    PERFORM pg_catalog.set_config(
        'app.current_tenant', COALESCE(prior_tenant, ''), true
    );
    RETURN;
END
$function$;
ALTER FUNCTION clinic_app.protected_blind_index(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
) OWNER TO clinic_owner;
REVOKE ALL ON FUNCTION clinic_app.protected_blind_index(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
) FROM PUBLIC, clinic_resolver;
GRANT EXECUTE ON FUNCTION clinic_app.protected_blind_index(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
) TO clinic_app;
"""

_REGISTRY_TENANT_CHECK: str = """
    IF NOT EXISTS (
        SELECT 1
          FROM clinic_app.identity_userclinicrole AS role_row
          JOIN clinic_app.identity_user AS user_row
            ON user_row.id = role_row.user_id AND user_row.is_active
         WHERE role_row.user_id = NULLIF(
             pg_catalog.current_setting('app.current_user_id', true), ''
         )::pg_catalog.uuid
           AND role_row.organization_id = NULLIF(
               pg_catalog.current_setting('app.current_tenant', true), ''
           )::pg_catalog.uuid
           AND role_row.clinic_id = requested_clinic
           AND role_row.role IN ('owner', 'clinic_admin', 'receptionist')
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '42501',
            MESSAGE = 'clinic manager authority is required';
    END IF;
"""

# The normalized substring predicate folds diacritics and case on both sides
# so unaccented queries match accented registrations (UX-04); ordering keeps
# the pinned lower(name)/birth_date/patient contract on decrypted names.
_REGISTRY_DECRYPTED_ROWS: str = """
        SELECT enrollment_row.id AS enrollment_id,
               patient_row.id AS patient_id,
               pg_catalog.convert_from(
                   clinic_app.protected_decrypt(
                       kek, 'intake.patient.full_name', patient_row.full_name
                   ),
                   'UTF8'
               ) COLLATE pg_catalog."default" AS decrypted_name,
               CASE WHEN patient_row.birth_date IS NULL THEN NULL
                    ELSE pg_catalog.convert_from(
                        clinic_app.protected_decrypt(
                            kek,
                            'intake.patient.birth_date',
                            patient_row.birth_date
                        ),
                        'UTF8'
                    )::pg_catalog.date
               END AS decrypted_birth,
               CASE WHEN demographics_row.social_name IS NULL THEN NULL
                    ELSE pg_catalog.convert_from(
                        clinic_app.protected_decrypt(
                            kek,
                            'intake.patientdemographics.social_name',
                            demographics_row.social_name
                        ),
                        'UTF8'
                    )
               END COLLATE pg_catalog."default" AS decrypted_social_name
          FROM clinic_app.intake_patientclinicenrollment AS enrollment_row
          JOIN clinic_app.intake_patient AS patient_row
            ON patient_row.id = enrollment_row.patient_id
           AND patient_row.organization_id = enrollment_row.organization_id
          LEFT JOIN clinic_app.intake_patientdemographics AS demographics_row
            ON demographics_row.organization_id = enrollment_row.organization_id
           AND demographics_row.patient_id = enrollment_row.patient_id
           AND demographics_row.version = (
               SELECT pg_catalog.max(latest_row.version)
                 FROM clinic_app.intake_patientdemographics AS latest_row
                WHERE latest_row.organization_id = enrollment_row.organization_id
                  AND latest_row.patient_id = enrollment_row.patient_id
           )
         WHERE enrollment_row.clinic_id = requested_clinic
           AND enrollment_row.organization_id = NULLIF(
               pg_catalog.current_setting('app.current_tenant', true), ''
           )::pg_catalog.uuid
"""

_REGISTRY_FOLDED_PREDICATE: str = """
        (pg_catalog.strpos(
            clinic_app.unaccent(
                pg_catalog.lower(decrypted.decrypted_name)
            ),
            clinic_app.unaccent(pg_catalog.lower(normalized_query))
        ) > 0
        OR pg_catalog.strpos(
            clinic_app.unaccent(
                pg_catalog.lower(
                    COALESCE(decrypted.decrypted_social_name, '')
                )
            ),
            clinic_app.unaccent(pg_catalog.lower(normalized_query))
        ) > 0)
"""

_REGISTRY_SQL: str = (
    """
CREATE OR REPLACE FUNCTION clinic_app.patient_registry_count(
    kek pg_catalog.text,
    requested_clinic pg_catalog.uuid,
    normalized_query pg_catalog.text,
    requested_birth pg_catalog.date
)
RETURNS pg_catalog.int8
LANGUAGE plpgsql
STABLE
PARALLEL UNSAFE
SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
DECLARE
    total pg_catalog.int8;
BEGIN
"""
    + _REGISTRY_TENANT_CHECK
    + """
    SELECT pg_catalog.count(*) INTO total
      FROM (
"""
    + _REGISTRY_DECRYPTED_ROWS
    + """
      ) AS decrypted
     WHERE """
    + _REGISTRY_FOLDED_PREDICATE
    + """
       AND (requested_birth IS NULL
            OR decrypted.decrypted_birth = requested_birth);
    RETURN total;
END
$function$;

DROP FUNCTION IF EXISTS clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
);
CREATE FUNCTION clinic_app.patient_registry_page(
    kek pg_catalog.text,
    requested_clinic pg_catalog.uuid,
    normalized_query pg_catalog.text,
    requested_birth pg_catalog.date,
    page_offset pg_catalog.int4,
    page_limit pg_catalog.int4
)
RETURNS TABLE(
    enrollment_id pg_catalog.uuid,
    full_name pg_catalog.text,
    birth_date pg_catalog.date,
    social_name pg_catalog.text
)
LANGUAGE plpgsql
STABLE
PARALLEL UNSAFE
SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
BEGIN
"""
    + _REGISTRY_TENANT_CHECK
    + """
    RETURN QUERY
    SELECT decrypted.enrollment_id, decrypted.decrypted_name,
           decrypted.decrypted_birth, decrypted.decrypted_social_name
      FROM (
"""
    + _REGISTRY_DECRYPTED_ROWS
    + """
      ) AS decrypted
     WHERE """
    + _REGISTRY_FOLDED_PREDICATE
    + """
       AND (requested_birth IS NULL
            OR decrypted.decrypted_birth = requested_birth)
     ORDER BY pg_catalog.lower(decrypted.decrypted_name),
              decrypted.decrypted_birth,
              decrypted.patient_id
     LIMIT page_limit OFFSET page_offset;
END
$function$;

ALTER FUNCTION clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
) OWNER TO clinic_owner;
ALTER FUNCTION clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
) OWNER TO clinic_owner;

REVOKE ALL ON FUNCTION clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
) FROM PUBLIC, clinic_resolver;
REVOKE ALL ON FUNCTION clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
) FROM PUBLIC, clinic_resolver;
GRANT EXECUTE ON FUNCTION clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
) TO clinic_app;
GRANT EXECUTE ON FUNCTION clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
) TO clinic_app;
GRANT EXECUTE ON FUNCTION clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
) TO clinic_owner;
GRANT EXECUTE ON FUNCTION clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
) TO clinic_owner;
"""
)

_OVERVIEW_SQL = """
-- The overview now prefers the recorded social name for the patient banner
-- while keeping the same signature, session re-validation and KEK boundary.
SET LOCAL ROLE clinic_resolver;
DROP FUNCTION IF EXISTS clinic_app.patient_session_overview(pg_catalog.text);
CREATE FUNCTION clinic_app.patient_session_overview(
    kek pg_catalog.text
)
RETURNS TABLE(
    session_id pg_catalog.uuid,
    patient_name pg_catalog.varchar,
    clinic_name pg_catalog.varchar,
    enrolled_at pg_catalog.timestamptz,
    operations pg_catalog.text[],
    expires_at pg_catalog.timestamptz,
    idle_expires_at pg_catalog.timestamptz
)
LANGUAGE sql
STABLE
PARALLEL UNSAFE
SECURITY DEFINER
ROWS 1
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
    SELECT session_row.id,
           CASE WHEN COALESCE(
                demographics_row.social_name, patient.full_name
           ) IS NULL THEN NULL
                ELSE pg_catalog.convert_from(
                    clinic_app.protected_decrypt(
                        kek,
                        CASE WHEN demographics_row.social_name IS NOT NULL
                             THEN 'intake.patientdemographics.social_name'
                             ELSE 'intake.patient.full_name'
                        END,
                        COALESCE(
                            demographics_row.social_name, patient.full_name
                        )
                    ),
                    'UTF8'
                )
           END,
           clinic.name,
           enrollment.created_at,
           session_row.operations::pg_catalog.text[],
           session_row.expires_at,
           session_row.idle_expires_at
    FROM clinic_app.intake_patientsession AS session_row
    JOIN clinic_app.intake_patientaccessgrant AS grant_row
      ON grant_row.id = session_row.grant_id
     AND grant_row.revoked_at IS NULL
    JOIN clinic_app.intake_patient AS patient
      ON patient.organization_id = session_row.organization_id
     AND patient.id = session_row.patient_id
    JOIN clinic_app.identity_clinic AS clinic
      ON clinic.organization_id = session_row.organization_id
     AND clinic.id = session_row.clinic_id
    JOIN clinic_app.intake_patientclinicenrollment AS enrollment
      ON enrollment.organization_id = session_row.organization_id
     AND enrollment.clinic_id = session_row.clinic_id
     AND enrollment.id = session_row.enrollment_id
    LEFT JOIN clinic_app.intake_patientdemographics AS demographics_row
      ON demographics_row.organization_id = session_row.organization_id
     AND demographics_row.patient_id = session_row.patient_id
     AND demographics_row.version = (
         SELECT pg_catalog.max(latest_row.version)
           FROM clinic_app.intake_patientdemographics AS latest_row
          WHERE latest_row.organization_id = session_row.organization_id
            AND latest_row.patient_id = session_row.patient_id
     )
    WHERE session_row.id = NULLIF(
        pg_catalog.current_setting('app.current_patient_session', true),
        ''
    )::pg_catalog.uuid
      AND session_row.revoked_at IS NULL
      AND session_row.expires_at > pg_catalog.now()
      AND session_row.idle_expires_at > pg_catalog.now()
$function$;
REVOKE ALL PRIVILEGES
    ON FUNCTION clinic_app.patient_session_overview(pg_catalog.text)
    FROM PUBLIC;
GRANT EXECUTE
    ON FUNCTION clinic_app.patient_session_overview(pg_catalog.text)
    TO clinic_app;
RESET ROLE;
"""

_RUNTIME_ACL_SQL = """
REVOKE ALL PRIVILEGES
    ON TABLE clinic_app.intake_patientdemographics,
             clinic_app.intake_demographicscorrection,
             clinic_app.intake_patientidentifier,
             clinic_app.intake_patientaddress,
             clinic_app.intake_emergencycontact,
             clinic_app.intake_insurancemembership,
             clinic_app.intake_clinicintakepolicy
    FROM PUBLIC, clinic_app, clinic_resolver;
-- Append-only history: the runtime role reads and appends versions only.
GRANT SELECT, INSERT
    ON TABLE clinic_app.intake_patientdemographics,
             clinic_app.intake_demographicscorrection,
             clinic_app.intake_patientidentifier,
             clinic_app.intake_patientaddress,
             clinic_app.intake_emergencycontact,
             clinic_app.intake_insurancemembership,
             clinic_app.intake_clinicintakepolicy
    TO clinic_app;
-- The registry row mirrors the latest version's name and birth date; the
-- mirror guard admits the change only alongside a new version.
GRANT UPDATE (full_name, birth_date) ON TABLE clinic_app.intake_patient
    TO clinic_app;
-- The resolver reads latest demographics for the session banner; this grant
-- must follow the blanket REVOKE above.
GRANT SELECT ON clinic_app.intake_patientdemographics TO clinic_resolver;
"""


def _sql_step(sql: str) -> Callable[[Apps, BaseDatabaseSchemaEditor], None]:
    """Run one SQL script as a single transaction (SET LOCAL stays scoped)."""

    def run(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
        del apps, schema_editor
        with transaction.atomic(), connection.cursor() as cursor:
            cursor.execute(sql)

    return run


def _step(sql: str) -> migrations.RunPython:
    # No reverse code: the operation is irreversible, so Django refuses an
    # unapply before touching the database. Rollback = restore.
    return migrations.RunPython(_sql_step(sql), atomic=True)


class Migration(migrations.Migration):
    """Create the encrypted identity-expansion tables and search boundary."""

    atomic = False
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("identity", "0013_permission_bundles"),
        ("intake", "0011_protected_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.AlterField(
            model_name="patient",
            name="birth_date",
            field=apps.tenancy.fields.EncryptedDateField(
                null=True, purpose="intake.patient.birth_date"
            ),
        ),
        migrations.CreateModel(
            name="PatientDemographics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "legal_name",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientdemographics.legal_name"
                    ),
                ),
                (
                    "social_name",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientdemographics.social_name"
                    ),
                ),
                (
                    "preferred_name",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientdemographics.preferred_name"
                    ),
                ),
                (
                    "sex_at_birth",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientdemographics.sex_at_birth"
                    ),
                ),
                (
                    "gender_identity",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientdemographics.gender_identity"
                    ),
                ),
                (
                    "pronouns",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientdemographics.pronouns"
                    ),
                ),
                (
                    "language",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientdemographics.language"
                    ),
                ),
                (
                    "accessibility_needs",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.patientdemographics.accessibility_needs",
                    ),
                ),
                (
                    "occupation",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientdemographics.occupation"
                    ),
                ),
                (
                    "birth_date",
                    apps.tenancy.fields.EncryptedDateField(
                        null=True, purpose="intake.patientdemographics.birth_date"
                    ),
                ),
                (
                    "unknown_fields",
                    apps.tenancy.fields.EncryptedJSONField(
                        null=True, purpose="intake.patientdemographics.unknown_fields"
                    ),
                ),
                (
                    "registry_full_name",
                    models.BinaryField(editable=False, null=True),
                ),
                (
                    "registry_birth_date",
                    models.BinaryField(editable=False, null=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("staff_recorded", "Staff recorded"),
                            ("patient_reported", "Reported by patient"),
                        ],
                        default="staff_recorded",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="identity.clinic",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="intake.patientclinicenrollment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="intake.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemographicsCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_label", models.CharField(max_length=150)),
                (
                    "reason",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.demographicscorrection.reason"
                    ),
                ),
                ("changed_fields", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="identity.clinic",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="intake.patient"
                    ),
                ),
                (
                    "demographics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="intake.patientdemographics",
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="intake.patientdemographics",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cpf", "CPF"),
                            ("cns", "CNS"),
                            ("rg", "RG"),
                            ("passport", "Passport"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "value",
                    apps.tenancy.fields.EncryptedTextField(
                        purpose="intake.patientidentifier.value"
                    ),
                ),
                ("blind_index", models.BinaryField(max_length=32)),
                ("index_key_version", models.PositiveIntegerField(default=1)),
                (
                    "issuer",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientidentifier.issuer"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="identity.clinic",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="intake.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClinicIntakePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("required_fields", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="identity.clinic",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="intake_policy_org_id_uniq"
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "clinic", "version"),
                        name="intake_policy_org_clinic_version_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="intake_policy_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=django.db.models.expressions.RawSQL(
                            "jsonb_typeof(required_fields) = 'array'",
                            (),
                            output_field=models.BooleanField(),
                        ),
                        name="intake_policy_fields_check",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
                (
                    "name",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.emergencycontact.name"
                    ),
                ),
                (
                    "relationship",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.emergencycontact.relationship"
                    ),
                ),
                (
                    "phone",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.emergencycontact.phone"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="intake.patient"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"),
                        name="intake_emergency_contact_org_id_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "patient", "sequence", "version"),
                        name="intake_emergency_contact_org_patient_seq_version_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1), ("sequence__lte", 3)),
                        name="intake_emergency_contact_sequence_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="intake_emergency_contact_version_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InsuranceMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
                (
                    "payer_name",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.insurancemembership.payer_name"
                    ),
                ),
                (
                    "ans_number",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.insurancemembership.ans_number"
                    ),
                ),
                (
                    "membership_number",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.insurancemembership.membership_number",
                    ),
                ),
                (
                    "plan_name",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.insurancemembership.plan_name"
                    ),
                ),
                (
                    "valid_until",
                    apps.tenancy.fields.EncryptedDateField(
                        null=True, purpose="intake.insurancemembership.valid_until"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="intake.patient"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"),
                        name="intake_membership_org_id_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "patient", "sequence", "version"),
                        name="intake_membership_org_patient_seq_version_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1), ("sequence__lte", 3)),
                        name="intake_membership_sequence_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="intake_membership_version_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PatientAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "postal_code",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientaddress.postal_code"
                    ),
                ),
                (
                    "street",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientaddress.street"
                    ),
                ),
                (
                    "street_number",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientaddress.street_number"
                    ),
                ),
                (
                    "complement",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientaddress.complement"
                    ),
                ),
                (
                    "district",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientaddress.district"
                    ),
                ),
                (
                    "city",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientaddress.city"
                    ),
                ),
                (
                    "state_code",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientaddress.state_code"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="intake.patient"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="intake_address_org_id_uniq"
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "patient", "kind", "version"),
                        name="intake_address_org_patient_kind_version_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["home", "other", "work"])),
                        name="intake_address_kind_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="intake_address_version_positive",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="patientdemographics",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="intake_demographics_org_id_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="patientdemographics",
            constraint=models.UniqueConstraint(
                fields=("organization", "patient", "version"),
                name="intake_demographics_org_patient_version_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientdemographics",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="intake_demographics_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientdemographics",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source__in", ["staff_recorded", "patient_reported"])
                ),
                name="intake_demographics_source_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="demographicscorrection",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"),
                name="intake_demographics_correction_org_id_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="demographicscorrection",
            constraint=models.UniqueConstraint(
                fields=("organization", "demographics"),
                name="intake_demographics_correction_version_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="demographicscorrection",
            constraint=models.CheckConstraint(
                condition=django.db.models.expressions.RawSQL(
                    "jsonb_typeof(changed_fields) = 'array'",
                    (),
                    output_field=models.BooleanField(),
                ),
                name="intake_demographics_correction_fields_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientidentifier",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="intake_identifier_org_id_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="patientidentifier",
            constraint=models.UniqueConstraint(
                fields=("organization", "patient", "kind", "version"),
                name="intake_identifier_org_patient_kind_version_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientidentifier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["cpf", "cns", "passport", "rg", "other"])
                ),
                name="intake_identifier_kind_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientidentifier",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="intake_identifier_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientidentifier",
            constraint=models.CheckConstraint(
                condition=django.db.models.expressions.RawSQL(
                    "pg_catalog.octet_length(blind_index) = 32",
                    (),
                    output_field=models.BooleanField(),
                ),
                name="intake_identifier_blind_index_32_check",
            ),
        ),
        _step(_EXTENSION_SQL),
        _step(_INTEGRITY_SQL),
        *(
            _step(apply_intake_rls(table, "organization_id"))
            for table in NEW_RLS_TABLES
        ),
        _step(_APPEND_ONLY_SQL),
        _step(_VERSION_GUARD_SQL),
        _step(_RECEIPT_GUARD_SQL),
        _step(_BLIND_INDEX_SQL),
        _step(_REGISTRY_SQL),
        _step(_OVERVIEW_SQL),
        _step(_RUNTIME_ACL_SQL),
    ]
