# Generated by hand for todo 17 patient identity expansion on 2026-09-25
# ruff: noqa: S608 - DDL text built from migration literals, never user input
"""Add versioned demographics, identifiers, contacts and correction history.

Additive only: seven intake tables ship already-encrypted columns plus the
append-only correction receipt, composite organization-scoped foreign keys,
FORCE RLS through the shared ``tenant_isolation`` helper and a REVOKE down
to the exact runtime grant set. Identifier exact search runs on a
tenant-keyed HMAC blind index computed inside the database boundary by the
new ``clinic_app.protected_blind_index`` (clinic_owner-owned SECURITY
DEFINER, mirroring ``protected_encrypt``); the plaintext value stays an
envelope. The registry search functions are re-created with a
diacritic-insensitive predicate (``unaccent`` + ``lower`` on both sides) so
'Joao' and 'João' match; the patient-session overview now prefers the
social name for the banner.

The migration is reversible: it creates no protected-column backfill and
drops what it adds on unapply.
"""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING, ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.tenancy.fields
from apps.intake.rls import apply_intake_rls, remove_intake_rls

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation

NEW_RLS_TABLES = (
    "intake_patientdemographics",
    "intake_demographicscorrection",
    "intake_patientidentifier",
    "intake_patientaddress",
    "intake_emergencycontact",
    "intake_insurancemembership",
    "intake_clinicintakepolicy",
)

_EXTENSION_SQL = """
DO $guard$
DECLARE
    installed_schema pg_catalog.text;
BEGIN
    SELECT namespace.nspname
      INTO installed_schema
      FROM pg_catalog.pg_extension AS extension
      JOIN pg_catalog.pg_namespace AS namespace
        ON namespace.oid = extension.extnamespace
     WHERE extension.extname = 'unaccent';

    IF installed_schema IS NOT NULL AND installed_schema <> 'clinic_app' THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'unaccent must be installed in clinic_app schema';
    END IF;
END
$guard$;

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA clinic_app;
"""

_INTEGRITY_SQL = """
ALTER TABLE clinic_app.intake_patientdemographics
    ADD CONSTRAINT intake_demographics_org_patient_fk
    FOREIGN KEY (organization_id, patient_id)
    REFERENCES clinic_app.intake_patient (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_patientdemographics
    ADD CONSTRAINT intake_demographics_org_clinic_fk
    FOREIGN KEY (organization_id, clinic_id)
    REFERENCES clinic_app.identity_clinic (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_patientdemographics
    ADD CONSTRAINT intake_demographics_org_enrollment_fk
    FOREIGN KEY (organization_id, clinic_id, enrollment_id)
    REFERENCES clinic_app.intake_patientclinicenrollment
        (organization_id, clinic_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_demographicscorrection
    ADD CONSTRAINT intake_correction_org_patient_fk
    FOREIGN KEY (organization_id, patient_id)
    REFERENCES clinic_app.intake_patient (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_demographicscorrection
    ADD CONSTRAINT intake_correction_org_clinic_fk
    FOREIGN KEY (organization_id, clinic_id)
    REFERENCES clinic_app.identity_clinic (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_demographicscorrection
    ADD CONSTRAINT intake_correction_org_demographics_fk
    FOREIGN KEY (organization_id, demographics_id)
    REFERENCES clinic_app.intake_patientdemographics (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_demographicscorrection
    ADD CONSTRAINT intake_correction_org_previous_fk
    FOREIGN KEY (organization_id, previous_id)
    REFERENCES clinic_app.intake_patientdemographics (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_patientidentifier
    ADD CONSTRAINT intake_identifier_org_patient_fk
    FOREIGN KEY (organization_id, patient_id)
    REFERENCES clinic_app.intake_patient (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_patientidentifier
    ADD CONSTRAINT intake_identifier_org_clinic_fk
    FOREIGN KEY (organization_id, clinic_id)
    REFERENCES clinic_app.identity_clinic (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_patientaddress
    ADD CONSTRAINT intake_address_org_patient_fk
    FOREIGN KEY (organization_id, patient_id)
    REFERENCES clinic_app.intake_patient (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_emergencycontact
    ADD CONSTRAINT intake_emergency_contact_org_patient_fk
    FOREIGN KEY (organization_id, patient_id)
    REFERENCES clinic_app.intake_patient (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_insurancemembership
    ADD CONSTRAINT intake_membership_org_patient_fk
    FOREIGN KEY (organization_id, patient_id)
    REFERENCES clinic_app.intake_patient (organization_id, id)
    NOT DEFERRABLE;
ALTER TABLE clinic_app.intake_clinicintakepolicy
    ADD CONSTRAINT intake_policy_org_clinic_fk
    FOREIGN KEY (organization_id, clinic_id)
    REFERENCES clinic_app.identity_clinic (organization_id, id)
    NOT DEFERRABLE;

CREATE FUNCTION clinic_app.intake_demographics_immutable_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, clinic_app
AS $function$
BEGIN
    RAISE EXCEPTION USING
        ERRCODE = '23514',
        CONSTRAINT = 'intake_demographics_immutable_check',
        MESSAGE = 'patient demographics versions are append-only';
END;
$function$;
REVOKE ALL ON FUNCTION clinic_app.intake_demographics_immutable_v1()
    FROM PUBLIC, clinic_app, clinic_resolver;
CREATE TRIGGER intake_demographics_immutable
BEFORE UPDATE OR DELETE ON clinic_app.intake_patientdemographics
FOR EACH ROW EXECUTE FUNCTION clinic_app.intake_demographics_immutable_v1();
CREATE TRIGGER intake_demographics_correction_immutable
BEFORE UPDATE OR DELETE ON clinic_app.intake_demographicscorrection
FOR EACH ROW EXECUTE FUNCTION clinic_app.intake_demographics_immutable_v1();
"""

_REVERSE_INTEGRITY_SQL = """
DROP TRIGGER IF EXISTS intake_demographics_immutable
    ON clinic_app.intake_patientdemographics;
DROP TRIGGER IF EXISTS intake_demographics_correction_immutable
    ON clinic_app.intake_demographicscorrection;
DROP FUNCTION IF EXISTS clinic_app.intake_demographics_immutable_v1();
ALTER TABLE clinic_app.intake_patientdemographics
    DROP CONSTRAINT intake_demographics_org_patient_fk,
    DROP CONSTRAINT intake_demographics_org_clinic_fk,
    DROP CONSTRAINT intake_demographics_org_enrollment_fk;
ALTER TABLE clinic_app.intake_demographicscorrection
    DROP CONSTRAINT intake_correction_org_patient_fk,
    DROP CONSTRAINT intake_correction_org_clinic_fk,
    DROP CONSTRAINT intake_correction_org_demographics_fk,
    DROP CONSTRAINT intake_correction_org_previous_fk;
ALTER TABLE clinic_app.intake_patientidentifier
    DROP CONSTRAINT intake_identifier_org_patient_fk,
    DROP CONSTRAINT intake_identifier_org_clinic_fk;
ALTER TABLE clinic_app.intake_patientaddress
    DROP CONSTRAINT intake_address_org_patient_fk;
ALTER TABLE clinic_app.intake_emergencycontact
    DROP CONSTRAINT intake_emergency_contact_org_patient_fk;
ALTER TABLE clinic_app.intake_insurancemembership
    DROP CONSTRAINT intake_membership_org_patient_fk;
ALTER TABLE clinic_app.intake_clinicintakepolicy
    DROP CONSTRAINT intake_policy_org_clinic_fk;
"""

_BLIND_INDEX_SQL = """
-- Tenant-keyed HMAC for exact-match identifier lookup. The DEK is unwrapped
-- per version inside the boundary so a lookup issued after a key rotation
-- still answers for rows indexed under retired versions; the caller picks
-- the highest-version digest for writes and tries every digest for reads.
-- The tenant resolves through protected_tenant(), so staff contexts set
-- app.current_tenant for the inner unwrap exactly like protected_encrypt.
CREATE FUNCTION clinic_app.protected_blind_index(
    kek pg_catalog.text,
    purpose pg_catalog.text,
    plaintext pg_catalog.bytea
)
RETURNS TABLE(
    blind_index pg_catalog.bytea,
    key_version pg_catalog.int4
)
LANGUAGE plpgsql
VOLATILE
PARALLEL UNSAFE
SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
DECLARE
    prior_tenant pg_catalog.text;
    resolved pg_catalog.uuid;
    key_row pg_catalog.record;
BEGIN
    resolved := clinic_app.protected_tenant();
    prior_tenant := pg_catalog.current_setting('app.current_tenant', true);
    PERFORM pg_catalog.set_config(
        'app.current_tenant', resolved::pg_catalog.text, true
    );
    IF kek IS NULL OR NOT kek ~ '^[0-9a-f]{64}$' THEN
        RAISE EXCEPTION USING ERRCODE = '22023',
            MESSAGE = 'wrapping key must be 32 bytes hex-encoded';
    END IF;
    IF purpose IS NULL
        OR pg_catalog.char_length(purpose) NOT BETWEEN 1 AND 128
        OR purpose ~ '[[:cntrl:]]'
    THEN
        RAISE EXCEPTION USING ERRCODE = '22023',
            MESSAGE = 'envelope purpose must be 1-128 printable characters';
    END IF;
    IF plaintext IS NULL THEN
        RAISE EXCEPTION USING ERRCODE = '22023',
            MESSAGE = 'envelope plaintext is required';
    END IF;
    FOR key_row IN
        SELECT version_row.key_version
          FROM clinic_app.tenancy_tenantdatakey AS version_row
         WHERE version_row.organization_id = resolved
         ORDER BY version_row.key_version
    LOOP
        blind_index := clinic_app.hmac(
            pg_catalog.convert_to(purpose, 'UTF8')
                || pg_catalog.decode('00', 'hex')
                || plaintext,
            clinic_app.tenant_dek_unwrap(kek, key_row.key_version),
            'sha256'
        );
        key_version := key_row.key_version;
        RETURN NEXT;
    END LOOP;
    PERFORM pg_catalog.set_config(
        'app.current_tenant', COALESCE(prior_tenant, ''), true
    );
    RETURN;
END
$function$;
ALTER FUNCTION clinic_app.protected_blind_index(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
) OWNER TO clinic_owner;
REVOKE ALL ON FUNCTION clinic_app.protected_blind_index(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
) FROM PUBLIC, clinic_resolver;
GRANT EXECUTE ON FUNCTION clinic_app.protected_blind_index(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
) TO clinic_app;
"""

_REVERSE_BLIND_INDEX_SQL = """
DROP FUNCTION IF EXISTS clinic_app.protected_blind_index(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
);
"""

_REGISTRY_TENANT_CHECK: str = """
    IF NOT EXISTS (
        SELECT 1
          FROM clinic_app.identity_userclinicrole AS role_row
          JOIN clinic_app.identity_user AS user_row
            ON user_row.id = role_row.user_id AND user_row.is_active
         WHERE role_row.user_id = NULLIF(
             pg_catalog.current_setting('app.current_user_id', true), ''
         )::pg_catalog.uuid
           AND role_row.organization_id = NULLIF(
               pg_catalog.current_setting('app.current_tenant', true), ''
           )::pg_catalog.uuid
           AND role_row.clinic_id = requested_clinic
           AND role_row.role IN ('owner', 'clinic_admin', 'receptionist')
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '42501',
            MESSAGE = 'clinic manager authority is required';
    END IF;
"""

# The normalized substring predicate folds diacritics and case on both sides
# so unaccented queries match accented registrations (UX-04); ordering keeps
# the pinned lower(name)/birth_date/patient contract on decrypted names.
_REGISTRY_DECRYPTED_ROWS: str = """
        SELECT enrollment_row.id AS enrollment_id,
               patient_row.id AS patient_id,
               pg_catalog.convert_from(
                   clinic_app.protected_decrypt(
                       kek, 'intake.patient.full_name', patient_row.full_name
                   ),
                   'UTF8'
               ) COLLATE pg_catalog."default" AS decrypted_name,
               pg_catalog.convert_from(
                   clinic_app.protected_decrypt(
                       kek,
                       'intake.patient.birth_date',
                       patient_row.birth_date
                   ),
                   'UTF8'
               )::pg_catalog.date AS decrypted_birth,
               CASE WHEN demographics_row.social_name IS NULL THEN NULL
                    ELSE pg_catalog.convert_from(
                        clinic_app.protected_decrypt(
                            kek,
                            'intake.patientdemographics.social_name',
                            demographics_row.social_name
                        ),
                        'UTF8'
                    )
               END COLLATE pg_catalog."default" AS decrypted_social_name
          FROM clinic_app.intake_patientclinicenrollment AS enrollment_row
          JOIN clinic_app.intake_patient AS patient_row
            ON patient_row.id = enrollment_row.patient_id
           AND patient_row.organization_id = enrollment_row.organization_id
          LEFT JOIN clinic_app.intake_patientdemographics AS demographics_row
            ON demographics_row.organization_id = enrollment_row.organization_id
           AND demographics_row.patient_id = enrollment_row.patient_id
           AND demographics_row.version = (
               SELECT pg_catalog.max(latest_row.version)
                 FROM clinic_app.intake_patientdemographics AS latest_row
                WHERE latest_row.organization_id = enrollment_row.organization_id
                  AND latest_row.patient_id = enrollment_row.patient_id
           )
         WHERE enrollment_row.clinic_id = requested_clinic
           AND enrollment_row.organization_id = NULLIF(
               pg_catalog.current_setting('app.current_tenant', true), ''
           )::pg_catalog.uuid
"""

_REGISTRY_FOLDED_PREDICATE: str = """
        (pg_catalog.strpos(
            clinic_app.unaccent(
                pg_catalog.lower(decrypted.decrypted_name)
            ),
            clinic_app.unaccent(pg_catalog.lower(normalized_query))
        ) > 0
        OR pg_catalog.strpos(
            clinic_app.unaccent(
                pg_catalog.lower(
                    COALESCE(decrypted.decrypted_social_name, '')
                )
            ),
            clinic_app.unaccent(pg_catalog.lower(normalized_query))
        ) > 0)
"""

_REGISTRY_SQL: str = (
    """
CREATE OR REPLACE FUNCTION clinic_app.patient_registry_count(
    kek pg_catalog.text,
    requested_clinic pg_catalog.uuid,
    normalized_query pg_catalog.text,
    requested_birth pg_catalog.date
)
RETURNS pg_catalog.int8
LANGUAGE plpgsql
STABLE
PARALLEL UNSAFE
SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
DECLARE
    total pg_catalog.int8;
BEGIN
"""
    + _REGISTRY_TENANT_CHECK
    + """
    SELECT pg_catalog.count(*) INTO total
      FROM (
"""
    + _REGISTRY_DECRYPTED_ROWS
    + """
      ) AS decrypted
     WHERE """
    + _REGISTRY_FOLDED_PREDICATE
    + """
       AND (requested_birth IS NULL
            OR decrypted.decrypted_birth = requested_birth);
    RETURN total;
END
$function$;

DROP FUNCTION IF EXISTS clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
);
CREATE FUNCTION clinic_app.patient_registry_page(
    kek pg_catalog.text,
    requested_clinic pg_catalog.uuid,
    normalized_query pg_catalog.text,
    requested_birth pg_catalog.date,
    page_offset pg_catalog.int4,
    page_limit pg_catalog.int4
)
RETURNS TABLE(
    enrollment_id pg_catalog.uuid,
    full_name pg_catalog.text,
    birth_date pg_catalog.date,
    social_name pg_catalog.text
)
LANGUAGE plpgsql
STABLE
PARALLEL UNSAFE
SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
BEGIN
"""
    + _REGISTRY_TENANT_CHECK
    + """
    RETURN QUERY
    SELECT decrypted.enrollment_id, decrypted.decrypted_name,
           decrypted.decrypted_birth, decrypted.decrypted_social_name
      FROM (
"""
    + _REGISTRY_DECRYPTED_ROWS
    + """
      ) AS decrypted
     WHERE """
    + _REGISTRY_FOLDED_PREDICATE
    + """
       AND (requested_birth IS NULL
            OR decrypted.decrypted_birth = requested_birth)
     ORDER BY pg_catalog.lower(decrypted.decrypted_name),
              decrypted.decrypted_birth,
              decrypted.patient_id
     LIMIT page_limit OFFSET page_offset;
END
$function$;

ALTER FUNCTION clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
) OWNER TO clinic_owner;
ALTER FUNCTION clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
) OWNER TO clinic_owner;

REVOKE ALL ON FUNCTION clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
) FROM PUBLIC, clinic_resolver;
REVOKE ALL ON FUNCTION clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
) FROM PUBLIC, clinic_resolver;
GRANT EXECUTE ON FUNCTION clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
) TO clinic_app;
GRANT EXECUTE ON FUNCTION clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
) TO clinic_app;
GRANT EXECUTE ON FUNCTION clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
) TO clinic_owner;
GRANT EXECUTE ON FUNCTION clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
) TO clinic_owner;
"""
)

# Unapply restores the pre-migration definitions exactly: no social_name
# join, the case-insensitive-only predicate and the three-column page shape.
_REGISTRY_LEGACY_DECRYPTED_ROWS: str = """
        SELECT enrollment_row.id AS enrollment_id,
               patient_row.id AS patient_id,
               pg_catalog.convert_from(
                   clinic_app.protected_decrypt(
                       kek, 'intake.patient.full_name', patient_row.full_name
                   ),
                   'UTF8'
               ) COLLATE pg_catalog."default" AS decrypted_name,
               pg_catalog.convert_from(
                   clinic_app.protected_decrypt(
                       kek,
                       'intake.patient.birth_date',
                       patient_row.birth_date
                   ),
                   'UTF8'
               )::pg_catalog.date AS decrypted_birth
          FROM clinic_app.intake_patientclinicenrollment AS enrollment_row
          JOIN clinic_app.intake_patient AS patient_row
            ON patient_row.id = enrollment_row.patient_id
           AND patient_row.organization_id = enrollment_row.organization_id
         WHERE enrollment_row.clinic_id = requested_clinic
           AND enrollment_row.organization_id = NULLIF(
               pg_catalog.current_setting('app.current_tenant', true), ''
           )::pg_catalog.uuid
"""

_REGISTRY_LEGACY_PREDICATE: str = """
        pg_catalog.strpos(
            pg_catalog.upper(decrypted.decrypted_name),
            pg_catalog.upper(normalized_query)
        ) > 0
"""

_REGISTRY_REVERSE_SQL: str = (
    """
CREATE OR REPLACE FUNCTION clinic_app.patient_registry_count(
    kek pg_catalog.text,
    requested_clinic pg_catalog.uuid,
    normalized_query pg_catalog.text,
    requested_birth pg_catalog.date
)
RETURNS pg_catalog.int8
LANGUAGE plpgsql
STABLE
PARALLEL UNSAFE
SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
DECLARE
    total pg_catalog.int8;
BEGIN
"""
    + _REGISTRY_TENANT_CHECK
    + """
    SELECT pg_catalog.count(*) INTO total
      FROM (
"""
    + _REGISTRY_LEGACY_DECRYPTED_ROWS
    + """
      ) AS decrypted
     WHERE """
    + _REGISTRY_LEGACY_PREDICATE
    + """
       AND (requested_birth IS NULL
            OR decrypted.decrypted_birth = requested_birth);
    RETURN total;
END
$function$;

DROP FUNCTION IF EXISTS clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
);
CREATE FUNCTION clinic_app.patient_registry_page(
    kek pg_catalog.text,
    requested_clinic pg_catalog.uuid,
    normalized_query pg_catalog.text,
    requested_birth pg_catalog.date,
    page_offset pg_catalog.int4,
    page_limit pg_catalog.int4
)
RETURNS TABLE(
    enrollment_id pg_catalog.uuid,
    full_name pg_catalog.text,
    birth_date pg_catalog.date
)
LANGUAGE plpgsql
STABLE
PARALLEL UNSAFE
SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
BEGIN
"""
    + _REGISTRY_TENANT_CHECK
    + """
    RETURN QUERY
    SELECT decrypted.enrollment_id, decrypted.decrypted_name,
           decrypted.decrypted_birth
      FROM (
"""
    + _REGISTRY_LEGACY_DECRYPTED_ROWS
    + """
      ) AS decrypted
     WHERE """
    + _REGISTRY_LEGACY_PREDICATE
    + """
       AND (requested_birth IS NULL
            OR decrypted.decrypted_birth = requested_birth)
     ORDER BY pg_catalog.lower(decrypted.decrypted_name),
              decrypted.decrypted_birth,
              decrypted.patient_id
     LIMIT page_limit OFFSET page_offset;
END
$function$;

ALTER FUNCTION clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
) OWNER TO clinic_owner;
ALTER FUNCTION clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
) OWNER TO clinic_owner;
REVOKE ALL ON FUNCTION clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
) FROM PUBLIC, clinic_resolver;
REVOKE ALL ON FUNCTION clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
) FROM PUBLIC, clinic_resolver;
GRANT EXECUTE ON FUNCTION clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
) TO clinic_app;
GRANT EXECUTE ON FUNCTION clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
) TO clinic_app;
"""
)

_OVERVIEW_SQL = """
-- The overview now prefers the recorded social name for the patient banner
-- while keeping the same signature, session re-validation and KEK boundary.
SET LOCAL ROLE clinic_resolver;
DROP FUNCTION IF EXISTS clinic_app.patient_session_overview(pg_catalog.text);
CREATE FUNCTION clinic_app.patient_session_overview(
    kek pg_catalog.text
)
RETURNS TABLE(
    session_id pg_catalog.uuid,
    patient_name pg_catalog.varchar,
    clinic_name pg_catalog.varchar,
    enrolled_at pg_catalog.timestamptz,
    operations pg_catalog.text[],
    expires_at pg_catalog.timestamptz,
    idle_expires_at pg_catalog.timestamptz
)
LANGUAGE sql
STABLE
PARALLEL UNSAFE
SECURITY DEFINER
ROWS 1
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
    SELECT session_row.id,
           CASE WHEN COALESCE(
                demographics_row.social_name, patient.full_name
           ) IS NULL THEN NULL
                ELSE pg_catalog.convert_from(
                    clinic_app.protected_decrypt(
                        kek,
                        CASE WHEN demographics_row.social_name IS NOT NULL
                             THEN 'intake.patientdemographics.social_name'
                             ELSE 'intake.patient.full_name'
                        END,
                        COALESCE(
                            demographics_row.social_name, patient.full_name
                        )
                    ),
                    'UTF8'
                )
           END,
           clinic.name,
           enrollment.created_at,
           session_row.operations::pg_catalog.text[],
           session_row.expires_at,
           session_row.idle_expires_at
    FROM clinic_app.intake_patientsession AS session_row
    JOIN clinic_app.intake_patientaccessgrant AS grant_row
      ON grant_row.id = session_row.grant_id
     AND grant_row.revoked_at IS NULL
    JOIN clinic_app.intake_patient AS patient
      ON patient.organization_id = session_row.organization_id
     AND patient.id = session_row.patient_id
    JOIN clinic_app.identity_clinic AS clinic
      ON clinic.organization_id = session_row.organization_id
     AND clinic.id = session_row.clinic_id
    JOIN clinic_app.intake_patientclinicenrollment AS enrollment
      ON enrollment.organization_id = session_row.organization_id
     AND enrollment.clinic_id = session_row.clinic_id
     AND enrollment.id = session_row.enrollment_id
    LEFT JOIN clinic_app.intake_patientdemographics AS demographics_row
      ON demographics_row.organization_id = session_row.organization_id
     AND demographics_row.patient_id = session_row.patient_id
     AND demographics_row.version = (
         SELECT pg_catalog.max(latest_row.version)
           FROM clinic_app.intake_patientdemographics AS latest_row
          WHERE latest_row.organization_id = session_row.organization_id
            AND latest_row.patient_id = session_row.patient_id
     )
    WHERE session_row.id = NULLIF(
        pg_catalog.current_setting('app.current_patient_session', true),
        ''
    )::pg_catalog.uuid
      AND session_row.revoked_at IS NULL
      AND session_row.expires_at > pg_catalog.now()
      AND session_row.idle_expires_at > pg_catalog.now()
$function$;
REVOKE ALL PRIVILEGES
    ON FUNCTION clinic_app.patient_session_overview(pg_catalog.text)
    FROM PUBLIC;
GRANT EXECUTE
    ON FUNCTION clinic_app.patient_session_overview(pg_catalog.text)
    TO clinic_app;
RESET ROLE;
"""

# Unapply restores the migration-0011 overview (legal name only) and drops
# the resolver read on the new demographics table before it disappears.
_OVERVIEW_REVERSE_SQL = """
SET LOCAL ROLE clinic_resolver;
DROP FUNCTION IF EXISTS clinic_app.patient_session_overview(pg_catalog.text);
CREATE FUNCTION clinic_app.patient_session_overview(
    kek pg_catalog.text
)
RETURNS TABLE(
    session_id pg_catalog.uuid,
    patient_name pg_catalog.varchar,
    clinic_name pg_catalog.varchar,
    enrolled_at pg_catalog.timestamptz,
    operations pg_catalog.text[],
    expires_at pg_catalog.timestamptz,
    idle_expires_at pg_catalog.timestamptz
)
LANGUAGE sql
STABLE
PARALLEL UNSAFE
SECURITY DEFINER
ROWS 1
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
    SELECT session_row.id,
           CASE WHEN patient.full_name IS NULL THEN NULL
                ELSE pg_catalog.convert_from(
                    clinic_app.protected_decrypt(
                        kek, 'intake.patient.full_name', patient.full_name
                    ),
                    'UTF8'
                )
           END,
           clinic.name,
           enrollment.created_at,
           session_row.operations::pg_catalog.text[],
           session_row.expires_at,
           session_row.idle_expires_at
    FROM clinic_app.intake_patientsession AS session_row
    JOIN clinic_app.intake_patientaccessgrant AS grant_row
      ON grant_row.id = session_row.grant_id
     AND grant_row.revoked_at IS NULL
    JOIN clinic_app.intake_patient AS patient
      ON patient.organization_id = session_row.organization_id
     AND patient.id = session_row.patient_id
    JOIN clinic_app.identity_clinic AS clinic
      ON clinic.organization_id = session_row.organization_id
     AND clinic.id = session_row.clinic_id
    JOIN clinic_app.intake_patientclinicenrollment AS enrollment
      ON enrollment.organization_id = session_row.organization_id
     AND enrollment.clinic_id = session_row.clinic_id
     AND enrollment.id = session_row.enrollment_id
    WHERE session_row.id = NULLIF(
        pg_catalog.current_setting('app.current_patient_session', true),
        ''
    )::pg_catalog.uuid
      AND session_row.revoked_at IS NULL
      AND session_row.expires_at > pg_catalog.now()
      AND session_row.idle_expires_at > pg_catalog.now()
$function$;
REVOKE ALL PRIVILEGES
    ON FUNCTION clinic_app.patient_session_overview(pg_catalog.text)
    FROM PUBLIC;
GRANT EXECUTE
    ON FUNCTION clinic_app.patient_session_overview(pg_catalog.text)
    TO clinic_app;
RESET ROLE;
REVOKE SELECT ON clinic_app.intake_patientdemographics FROM clinic_resolver;
"""

_RUNTIME_ACL_SQL = """
REVOKE ALL PRIVILEGES
    ON TABLE clinic_app.intake_patientdemographics,
             clinic_app.intake_demographicscorrection,
             clinic_app.intake_patientidentifier,
             clinic_app.intake_patientaddress,
             clinic_app.intake_emergencycontact,
             clinic_app.intake_insurancemembership,
             clinic_app.intake_clinicintakepolicy
    FROM PUBLIC, clinic_app, clinic_resolver;
GRANT SELECT, INSERT
    ON TABLE clinic_app.intake_patientdemographics,
             clinic_app.intake_demographicscorrection,
             clinic_app.intake_patientaddress,
             clinic_app.intake_emergencycontact,
             clinic_app.intake_insurancemembership,
             clinic_app.intake_clinicintakepolicy
    TO clinic_app;
GRANT SELECT, INSERT ON TABLE clinic_app.intake_patientidentifier
    TO clinic_app;
GRANT UPDATE (
    value, blind_index, index_key_version, issuer, version,
    retired_at, updated_at
) ON TABLE clinic_app.intake_patientidentifier TO clinic_app;
GRANT UPDATE (
    postal_code, street, street_number, complement, district, city,
    state_code, version, retired_at, updated_at
) ON TABLE clinic_app.intake_patientaddress TO clinic_app;
GRANT UPDATE (
    name, relationship, phone, version, retired_at, updated_at
) ON TABLE clinic_app.intake_emergencycontact TO clinic_app;
GRANT UPDATE (
    payer_name, ans_number, membership_number, plan_name, valid_until,
    version, retired_at, updated_at
) ON TABLE clinic_app.intake_insurancemembership TO clinic_app;
-- Corrections mirror legal_name back onto the registry row so name search
-- and the banner stay consistent; the grant is column-scoped.
GRANT UPDATE (full_name) ON TABLE clinic_app.intake_patient TO clinic_app;
-- The resolver reads latest demographics for the session banner; this grant
-- must follow the blanket REVOKE above.
GRANT SELECT ON clinic_app.intake_patientdemographics TO clinic_resolver;
"""

_REVERSE_RUNTIME_ACL_SQL = """
REVOKE ALL PRIVILEGES
    ON TABLE clinic_app.intake_patientdemographics,
             clinic_app.intake_demographicscorrection,
             clinic_app.intake_patientidentifier,
             clinic_app.intake_patientaddress,
             clinic_app.intake_emergencycontact,
             clinic_app.intake_insurancemembership,
             clinic_app.intake_clinicintakepolicy
    FROM clinic_app, clinic_resolver;
REVOKE UPDATE (full_name) ON TABLE clinic_app.intake_patient FROM clinic_app;
"""


class Migration(migrations.Migration):
    """Create the encrypted identity-expansion tables and search boundary."""

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("intake", "0011_protected_fields"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.CreateModel(
            name="PatientDemographics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "legal_name",
                    apps.tenancy.fields.EncryptedPatientNameField(
                        null=True,
                        purpose="intake.patientdemographics.legal_name",
                    ),
                ),
                (
                    "social_name",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.patientdemographics.social_name",
                    ),
                ),
                (
                    "preferred_name",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.patientdemographics.preferred_name",
                    ),
                ),
                (
                    "sex_at_birth",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.patientdemographics.sex_at_birth",
                    ),
                ),
                (
                    "gender_identity",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.patientdemographics.gender_identity",
                    ),
                ),
                (
                    "pronouns",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.patientdemographics.pronouns",
                    ),
                ),
                (
                    "language",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.patientdemographics.language",
                    ),
                ),
                (
                    "accessibility_needs",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.patientdemographics.accessibility_needs",
                    ),
                ),
                (
                    "occupation",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.patientdemographics.occupation",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("staff_recorded", "Staff recorded"),
                            ("patient_reported", "Reported by patient"),
                        ],
                        default="staff_recorded",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="identity.clinic",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="intake.patientclinicenrollment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="intake.patient",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"),
                        name="intake_demographics_org_id_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "patient", "version"),
                        name="intake_demographics_org_patient_version_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(version__gte=1),
                        name="intake_demographics_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            source__in=["staff_recorded", "patient_reported"]
                        ),
                        name="intake_demographics_source_check",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DemographicsCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_label", models.CharField(max_length=150)),
                (
                    "reason",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.demographicscorrection.reason",
                    ),
                ),
                ("changed_fields", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="identity.clinic",
                    ),
                ),
                (
                    "demographics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="intake.patientdemographics",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="intake.patient",
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="intake.patientdemographics",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"),
                        name="intake_demographics_correction_org_id_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "demographics"),
                        name="intake_demographics_correction_version_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.expressions.RawSQL(
                            "jsonb_typeof(changed_fields) = 'array'",
                            (),
                            output_field=models.BooleanField(),
                        ),
                        name="intake_demographics_correction_fields_check",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PatientIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cpf", "CPF"),
                            ("cns", "CNS"),
                            ("rg", "RG"),
                            ("passport", "Passport"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "value",
                    apps.tenancy.fields.EncryptedTextField(
                        purpose="intake.patientidentifier.value"
                    ),
                ),
                ("blind_index", models.BinaryField(editable=False, max_length=32)),
                ("index_key_version", models.PositiveIntegerField(default=1)),
                (
                    "issuer",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientidentifier.issuer"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="identity.clinic",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="intake.patient",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"),
                        name="intake_identifier_org_id_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "patient", "kind"),
                        name="intake_identifier_org_patient_kind_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            kind__in=["cpf", "cns", "passport", "rg", "other"]
                        ),
                        name="intake_identifier_kind_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(version__gte=1),
                        name="intake_identifier_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.expressions.RawSQL(
                            "pg_catalog.octet_length(blind_index) = 32",
                            (),
                            output_field=models.BooleanField(),
                        ),
                        name="intake_identifier_blind_index_32_check",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PatientAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "postal_code",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientaddress.postal_code"
                    ),
                ),
                (
                    "street",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientaddress.street"
                    ),
                ),
                (
                    "street_number",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientaddress.street_number"
                    ),
                ),
                (
                    "complement",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientaddress.complement"
                    ),
                ),
                (
                    "district",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientaddress.district"
                    ),
                ),
                (
                    "city",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientaddress.city"
                    ),
                ),
                (
                    "state_code",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.patientaddress.state_code"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="intake.patient",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"),
                        name="intake_address_org_id_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "patient", "kind"),
                        name="intake_address_org_patient_kind_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(kind__in=["home", "other", "work"]),
                        name="intake_address_kind_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(version__gte=1),
                        name="intake_address_version_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
                (
                    "name",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.emergencycontact.name"
                    ),
                ),
                (
                    "relationship",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.emergencycontact.relationship"
                    ),
                ),
                (
                    "phone",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True, purpose="intake.emergencycontact.phone"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="intake.patient",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"),
                        name="intake_emergency_contact_org_id_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "patient", "sequence"),
                        name="intake_emergency_contact_org_patient_seq_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(sequence__gte=1) & models.Q(sequence__lte=3),
                        name="intake_emergency_contact_sequence_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(version__gte=1),
                        name="intake_emergency_contact_version_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InsuranceMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
                (
                    "payer_name",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.insurancemembership.payer_name",
                    ),
                ),
                (
                    "ans_number",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.insurancemembership.ans_number",
                    ),
                ),
                (
                    "membership_number",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.insurancemembership.membership_number",
                    ),
                ),
                (
                    "plan_name",
                    apps.tenancy.fields.EncryptedTextField(
                        null=True,
                        purpose="intake.insurancemembership.plan_name",
                    ),
                ),
                (
                    "valid_until",
                    apps.tenancy.fields.EncryptedDateField(
                        null=True,
                        purpose="intake.insurancemembership.valid_until",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="intake.patient",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"),
                        name="intake_membership_org_id_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "patient", "sequence"),
                        name="intake_membership_org_patient_seq_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(sequence__gte=1) & models.Q(sequence__lte=3),
                        name="intake_membership_sequence_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(version__gte=1),
                        name="intake_membership_version_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClinicIntakePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("required_fields", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="identity.clinic",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"),
                        name="intake_policy_org_id_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "clinic", "version"),
                        name="intake_policy_org_clinic_version_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(version__gte=1),
                        name="intake_policy_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.expressions.RawSQL(
                            "jsonb_typeof(required_fields) = 'array'",
                            (),
                            output_field=models.BooleanField(),
                        ),
                        name="intake_policy_fields_check",
                    ),
                ],
            },
        ),
        migrations.RunSQL(sql=_EXTENSION_SQL, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql=_INTEGRITY_SQL, reverse_sql=_REVERSE_INTEGRITY_SQL),
        *(
            migrations.RunSQL(
                sql=apply_intake_rls(table, "organization_id"),
                reverse_sql=remove_intake_rls(table, "organization_id"),
            )
            for table in sorted(NEW_RLS_TABLES)
        ),
        migrations.RunSQL(sql=_BLIND_INDEX_SQL, reverse_sql=_REVERSE_BLIND_INDEX_SQL),
        migrations.RunSQL(sql=_REGISTRY_SQL, reverse_sql=_REGISTRY_REVERSE_SQL),
        migrations.RunSQL(sql=_OVERVIEW_SQL, reverse_sql=_OVERVIEW_REVERSE_SQL),
        migrations.RunSQL(sql=_RUNTIME_ACL_SQL, reverse_sql=_REVERSE_RUNTIME_ACL_SQL),
    ]
