# Generated by hand for the task-43 protected-field integration on 2026-09-22
"""Encrypt clinical SOAP content, history text and discarded archives.

``ehr_clinicaldocumentversion`` loses its four plaintext SOAP columns and
plaintext ``amendment_reason``: content becomes one tenant-envelope ``bytea``
plus ``content_sha256`` (the plaintext digest the binding trigger compares
across transitions), and discarded rows archive the envelope into
``ehr_discarded_content.content`` instead of blanked plaintext. Both the
envelope plaintext and its digest use the runtime's RFC 8785 canonical JSON
encoding so a migrated digest equals the digest ``set_soap`` recomputes when
an amendment draft carries the base version's content.
``ehr_historyassessment.reason`` and ``ehr_problem``/``ehr_allergy``
``description`` become envelope columns.

The binding and history guards are recreated for the new types: ciphertext
equality is meaningless, so content identity across amendment/supersede is
proven by the stored plaintext digest, and blank-content checks move to the
service layer (which already validates them) plus the digest invariant.
Every database operation is idempotent; the migration is irreversible
because rollback must never reactivate plaintext storage.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

import rfc8785
from django.db import migrations, models

import apps.tenancy.fields
from apps.tenancy.migrations._protected_migration import (
    add_constraint_sql,
    drop_constraint_sql,
    drop_legacy_sql,
    encrypt_backfill,
    irreversible,
    rename_to_legacy_sql,
    require_backfill_complete,
)

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.operations.base import Operation

_SOAP_KEYS = ("subjective", "objective", "assessment", "plan")


def _encode_text(value: object) -> bytes | None:
    if value is None or value == "":
        return None
    return str(value).encode("utf-8")


def _encode_soap(row: dict[str, object]) -> bytes | None:
    if row["state"] == "discarded":
        return None
    return rfc8785.dumps({key: str(row[f"{key}_legacy"] or "") for key in _SOAP_KEYS})


def _encode_archived_soap(row: dict[str, object]) -> bytes | None:
    return rfc8785.dumps({key: str(row[f"{key}_legacy"] or "") for key in _SOAP_KEYS})


_VERSION_PLANS = (
    (
        "content",
        "ehr.clinicaldocumentversion.content",
        tuple(f"{key}_legacy" for key in _SOAP_KEYS),
        ("state",),
        _encode_soap,
        "content_sha256",
    ),
    (
        "amendment_reason",
        "ehr.clinicaldocumentversion.amendment_reason",
        ("amendment_reason_legacy",),
        (),
        lambda row: _encode_text(row["amendment_reason_legacy"]),
        None,
    ),
)
_DISCARDED_PLANS = (
    (
        "content",
        "ehr.clinicaldocumentversion.content",
        tuple(f"{key}_legacy" for key in _SOAP_KEYS),
        (),
        _encode_archived_soap,
        "content_sha256",
    ),
)
_ASSESSMENT_PLANS = (
    (
        "reason",
        "ehr.historyassessment.reason",
        ("reason_legacy",),
        (),
        lambda row: _encode_text(row["reason_legacy"]),
        None,
    ),
)
_PROBLEM_PLANS = (
    (
        "description",
        "ehr.entryversion.description",
        ("description_legacy",),
        (),
        lambda row: _encode_text(row["description_legacy"]),
        None,
    ),
)
_ALLERGY_PLANS = _PROBLEM_PLANS

_SCHEMA_SQL = (
    "".join(
        rename_to_legacy_sql("ehr_clinicaldocumentversion", column)
        for column in (*_SOAP_KEYS, "amendment_reason")
    )
    + """
ALTER TABLE clinic_app.ehr_clinicaldocumentversion
    ADD COLUMN IF NOT EXISTS content pg_catalog.bytea,
    ADD COLUMN IF NOT EXISTS content_sha256 pg_catalog.text
        NOT NULL DEFAULT '';
"""
    + "".join(
        rename_to_legacy_sql("ehr_discarded_content", column) for column in _SOAP_KEYS
    )
    + """
ALTER TABLE clinic_app.ehr_discarded_content
    ADD COLUMN IF NOT EXISTS content pg_catalog.bytea,
    ADD COLUMN IF NOT EXISTS content_sha256 pg_catalog.text
        NOT NULL DEFAULT '';
"""
    + rename_to_legacy_sql("ehr_historyassessment", "reason")
    + rename_to_legacy_sql("ehr_problem", "description")
    + rename_to_legacy_sql("ehr_allergy", "description")
    + drop_constraint_sql("ehr_clinicaldocumentversion", "ehr_version_amendment_check")
    + drop_constraint_sql("ehr_problem", "problem_description_required")
    + drop_constraint_sql("ehr_allergy", "allergy_description_required")
    + add_constraint_sql(
        "ehr_clinicaldocumentversion",
        "ehr_version_amendment_check",
        "(amendment_of_id IS NULL AND amendment_reason IS NULL) OR "
        "(amendment_of_id IS NOT NULL AND amendment_reason IS NOT NULL "
        "AND version >= 2)",
    )
    + add_constraint_sql(
        "ehr_clinicaldocumentversion",
        "ehr_version_content_check",
        "(content IS NULL AND content_sha256 = '') OR "
        "(content IS NOT NULL AND content_sha256 ~ '^[0-9a-f]{64}$')",
    )
    + add_constraint_sql(
        "ehr_problem",
        "problem_description_required",
        "pg_catalog.octet_length(description) > 0",
    )
    + add_constraint_sql(
        "ehr_allergy",
        "allergy_description_required",
        "pg_catalog.octet_length(description) > 0",
    )
    + """
GRANT UPDATE (content, content_sha256, amendment_reason)
    ON clinic_app.ehr_clinicaldocumentversion TO clinic_app;
"""
)

_GUARD_SQL = """
SET LOCAL ROLE clinic_resolver;
CREATE OR REPLACE FUNCTION clinic_app.ehr_binding_guard()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp AS $f$
DECLARE
 encounter_row clinic_app.ehr_encounter;
 document_row clinic_app.ehr_clinicaldocument;
 base_row clinic_app.ehr_clinicaldocumentversion;
 latest integer;
BEGIN
 IF TG_TABLE_NAME = 'ehr_encounter' THEN
   IF NOT EXISTS (SELECT 1 FROM clinic_app.scheduling_appointment a
     JOIN clinic_app.intake_patientclinicenrollment p
       ON p.patient_id = a.patient_id AND p.clinic_id = a.clinic_id
       AND p.organization_id = a.organization_id
     WHERE a.id = NEW.appointment_id AND a.organization_id = NEW.organization_id
       AND a.clinic_id = NEW.clinic_id AND a.patient_id = NEW.patient_id
       AND a.practitioner_id = NEW.physician_id AND a.status = 'scheduled')
     OR NEW.state <> 'open' OR NEW.revision <> 1 THEN
      RAISE EXCEPTION 'invalid encounter binding' USING ERRCODE = '23514';
   END IF;
 ELSIF TG_TABLE_NAME = 'ehr_specialtytemplate' THEN
   IF NOT EXISTS (SELECT 1 FROM clinic_app.identity_clinic c
      WHERE c.id = NEW.clinic_id AND c.organization_id = NEW.organization_id)
      OR jsonb_typeof(NEW.prompts) <> 'object'
      OR NOT (NEW.prompts ?& ARRAY['subjective','objective','assessment','plan'])
      OR (NEW.prompts - ARRAY['subjective','objective','assessment','plan'])
         <> '{}'::jsonb THEN
     RAISE EXCEPTION 'invalid template binding' USING ERRCODE = '23514';
   END IF;
 ELSIF TG_TABLE_NAME = 'ehr_clinicaldocument' THEN
   SELECT * INTO encounter_row FROM clinic_app.ehr_encounter
     WHERE id = NEW.encounter_id;
   IF encounter_row.id IS NULL
      OR encounter_row.organization_id <> NEW.organization_id
      OR encounter_row.state <> 'open' OR NEW.kind <> 'soap' THEN
     RAISE EXCEPTION 'invalid document binding' USING ERRCODE = '23514';
   END IF;
 ELSIF TG_TABLE_NAME = 'ehr_clinicaldocumentversion' THEN
   SELECT * INTO document_row FROM clinic_app.ehr_clinicaldocument
     WHERE id = NEW.document_id;
   SELECT * INTO encounter_row FROM clinic_app.ehr_encounter
     WHERE id = document_row.encounter_id;
   IF document_row.id IS NULL OR document_row.organization_id <> NEW.organization_id
      OR encounter_row.physician_id <> NEW.author_id
      OR NOT EXISTS (SELECT 1 FROM clinic_app.ehr_specialtytemplate t
         WHERE t.id = NEW.template_id AND t.clinic_id = encounter_row.clinic_id
         AND t.organization_id = NEW.organization_id) THEN
     RAISE EXCEPTION 'invalid version binding' USING ERRCODE = '23514';
   END IF;
   IF TG_OP = 'INSERT' THEN
     -- Serialize draft creation against a concurrent encounter close: the
     -- close guard takes the same transaction-scoped advisory lock while it
     -- holds the encounter row lock, so this wait ends with the committed
     -- encounter state visible to the re-read below.
     PERFORM pg_catalog.pg_advisory_xact_lock(
       hashtextextended('ehr-encounter:' || document_row.encounter_id::text,
                        0));
     SELECT * INTO encounter_row FROM clinic_app.ehr_encounter
       WHERE id = document_row.encounter_id;
     IF NEW.state <> 'draft' OR NEW.revision <> 1
        OR NEW.content_digest <> '' OR NEW.finalized_at IS NOT NULL THEN
       RAISE EXCEPTION 'invalid initial draft' USING ERRCODE = '23514';
     END IF;
     SELECT max(version) INTO latest FROM clinic_app.ehr_clinicaldocumentversion
       WHERE document_id = NEW.document_id;
     IF NEW.version <> coalesce(latest, 0) + 1 THEN
       RAISE EXCEPTION 'invalid version sequence' USING ERRCODE = '23514';
     END IF;
     IF NEW.amendment_of_id IS NULL THEN
       IF encounter_row.state <> 'open'
          OR NEW.content IS NOT NULL OR NEW.content_sha256 <> ''
          OR NEW.amendment_reason IS NOT NULL
          OR EXISTS (SELECT 1 FROM clinic_app.ehr_clinicaldocumentversion v
            WHERE v.document_id = NEW.document_id
            AND v.state IN ('finalized','superseded')) THEN
         RAISE EXCEPTION 'invalid initial draft' USING ERRCODE = '23514';
       END IF;
     ELSE
       SELECT * INTO base_row FROM clinic_app.ehr_clinicaldocumentversion
         WHERE id = NEW.amendment_of_id;
       -- The amendment draft must carry the base version's exact content:
       -- ciphertext bytes differ across envelopes, so the stored plaintext
       -- digest is the equality proof.
       IF base_row.id IS NULL OR base_row.document_id <> NEW.document_id
          OR base_row.state <> 'finalized' OR NEW.amendment_reason IS NULL
          OR NEW.template_id <> base_row.template_id
          OR NEW.content IS NULL
          OR NEW.content_sha256 IS DISTINCT FROM base_row.content_sha256 THEN
         RAISE EXCEPTION 'invalid amendment draft' USING ERRCODE = '23514';
       END IF;
     END IF;
   ELSE
     IF (NEW.id,NEW.organization_id,NEW.document_id,NEW.template_id,NEW.author_id,
         NEW.amendment_of_id,NEW.amendment_reason,NEW.version,NEW.created_at)
        IS DISTINCT FROM
        (OLD.id,OLD.organization_id,OLD.document_id,OLD.template_id,OLD.author_id,
         OLD.amendment_of_id,OLD.amendment_reason,OLD.version,OLD.created_at) THEN
       RAISE EXCEPTION 'immutable version identity' USING ERRCODE = '23514';
     END IF;
     IF OLD.state = 'draft' AND NEW.state = 'draft' THEN
       IF NEW.revision <> OLD.revision + 1
          OR NEW.content_digest <> '' OR NEW.finalized_at IS NOT NULL
          OR NEW.content IS NULL
          OR NEW.content_sha256 !~ '^[0-9a-f]{64}$'
          OR (NEW.content IS DISTINCT FROM OLD.content)
             <> (NEW.content_sha256 IS DISTINCT FROM OLD.content_sha256) THEN
         RAISE EXCEPTION 'immutable version or stale revision'
           USING ERRCODE = '23514';
       END IF;
     ELSIF OLD.state = 'draft' AND NEW.state = 'finalized' THEN
       IF NEW.revision <> OLD.revision
          OR (NEW.content, NEW.content_sha256)
             IS DISTINCT FROM (OLD.content, OLD.content_sha256)
          OR NEW.content IS NULL
          OR NEW.content_sha256 !~ '^[0-9a-f]{64}$'
          OR NEW.content_digest !~ '^[0-9a-f]{64}$'
          OR NEW.finalized_at IS NULL THEN
         RAISE EXCEPTION 'invalid finalization' USING ERRCODE = '23514';
       END IF;
     ELSIF OLD.state = 'draft' AND NEW.state = 'discarded' THEN
       IF (NEW.revision,NEW.content_digest,NEW.finalized_at)
          IS DISTINCT FROM
          (OLD.revision,OLD.content_digest,OLD.finalized_at) THEN
         RAISE EXCEPTION 'invalid discard' USING ERRCODE = '23514';
       END IF;
       -- Discarded rows expose metadata only: the encrypted SOAP body moves
       -- to the owner-only archive and the stored row loses its envelope.
       INSERT INTO clinic_app.ehr_discarded_content
         (version_id,organization_id,document_id,author_id,
          content,content_sha256)
       VALUES (OLD.id,OLD.organization_id,OLD.document_id,OLD.author_id,
               OLD.content,OLD.content_sha256);
       NEW.content := NULL;
       NEW.content_sha256 := '';
     ELSIF OLD.state = 'finalized' AND NEW.state = 'superseded' THEN
       IF (NEW.content,NEW.content_sha256,NEW.revision,
           NEW.content_digest,NEW.finalized_at)
          IS DISTINCT FROM
          (OLD.content,OLD.content_sha256,OLD.revision,
           OLD.content_digest,OLD.finalized_at)
          OR NOT EXISTS (SELECT 1 FROM clinic_app.ehr_clinicaldocumentversion v
            WHERE v.document_id = OLD.document_id AND v.state = 'draft'
            AND v.amendment_of_id = OLD.id) THEN
         RAISE EXCEPTION 'invalid supersede' USING ERRCODE = '23514';
       END IF;
     ELSE
       RAISE EXCEPTION 'immutable version or stale revision'
         USING ERRCODE = '23514';
     END IF;
   END IF;
   IF NEW.content IS NOT NULL
      AND pg_catalog.octet_length(NEW.content) > 120000 THEN
     RAISE EXCEPTION 'SOAP content limit' USING ERRCODE = '23514';
   END IF;
 ELSIF TG_TABLE_NAME = 'ehr_encounterintakereference' THEN
   SELECT * INTO encounter_row FROM clinic_app.ehr_encounter
     WHERE id = NEW.encounter_id;
   IF encounter_row.id IS NULL
      OR encounter_row.organization_id <> NEW.organization_id
      OR NOT EXISTS (SELECT 1 FROM clinic_app.intake_questionnaireevent q
       JOIN clinic_app.intake_questionnaireresponse r ON r.id = q.response_id
       WHERE q.id = NEW.submission_id AND q.action = 'submitted'
       AND q.organization_id = NEW.organization_id
       AND q.clinic_id = encounter_row.clinic_id
       AND r.patient_id = encounter_row.patient_id
       AND (r.appointment_id IS NULL
         OR r.appointment_id = encounter_row.appointment_id)) THEN
     RAISE EXCEPTION 'invalid intake reference' USING ERRCODE = '23514';
   END IF;
 END IF;
 RETURN NEW;
END
$f$;

CREATE OR REPLACE FUNCTION clinic_app.ehr_history_guard()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp AS $f$
DECLARE
 e clinic_app.ehr_encounter;
 h clinic_app.ehr_historyassessment;
 previous record;
 latest integer;
 category text;
BEGIN
 IF TG_TABLE_NAME='ehr_historyassessment' THEN
   SELECT * INTO e FROM clinic_app.ehr_encounter WHERE id=NEW.encounter_id;
   IF e.id IS NULL OR (e.organization_id,e.clinic_id,e.patient_id,e.physician_id)
     IS DISTINCT FROM (NEW.organization_id,NEW.clinic_id,NEW.patient_id,NEW.author_id)
     OR NOT clinic_app.ehr_assigned(e.id) OR NEW.reason IS NULL THEN
     RAISE EXCEPTION 'invalid history authority or binding' USING ERRCODE='23514';
   END IF;
   PERFORM pg_advisory_xact_lock(hashtextextended(
      'ehr-history:'||NEW.clinic_id||':'||NEW.patient_id||':'||NEW.kind,0));
   SELECT coalesce(max(revision),0) INTO latest FROM clinic_app.ehr_historyassessment
     WHERE clinic_id=NEW.clinic_id AND patient_id=NEW.patient_id AND kind=NEW.kind;
   IF NEW.revision<>latest+1 THEN
     RAISE EXCEPTION 'stale history revision' USING ERRCODE='23514';
   END IF;
   IF NEW.state<>'documented' AND EXISTS (
       SELECT 1 FROM clinic_app.ehr_historyassessment
       WHERE clinic_id=NEW.clinic_id AND patient_id=NEW.patient_id
         AND kind=NEW.kind AND state='documented') THEN
     RAISE EXCEPTION 'documented history cannot imply absence' USING ERRCODE='23514';
   END IF;
   SELECT username INTO NEW.author_label FROM clinic_app.identity_user
      WHERE id=NEW.author_id;
   NEW.created_at=clock_timestamp();
 ELSE
   SELECT * INTO h FROM clinic_app.ehr_historyassessment WHERE id=NEW.assessment_id;
   category=CASE WHEN TG_TABLE_NAME='ehr_problem' THEN 'problem' ELSE 'allergy' END;
   IF h.id IS NULL OR h.organization_id<>NEW.organization_id
      OR h.kind<>category OR h.state<>'documented'
      OR NOT clinic_app.ehr_assigned(h.encounter_id)
      OR NEW.description IS NULL THEN
     RAISE EXCEPTION 'invalid history entry binding' USING ERRCODE='23514';
   END IF;
   PERFORM pg_advisory_xact_lock(hashtextextended(
      'ehr-history:'||h.clinic_id||':'||h.patient_id||':'||h.kind,0));
   SELECT max(revision) INTO latest FROM clinic_app.ehr_historyassessment
     WHERE clinic_id=h.clinic_id AND patient_id=h.patient_id AND kind=h.kind;
   IF latest<>h.revision THEN
     RAISE EXCEPTION 'stale assessment binding' USING ERRCODE='23514';
   END IF;
   IF category='problem' THEN
     SELECT v.version,ha.clinic_id,ha.patient_id,ha.encounter_id INTO previous
        FROM clinic_app.ehr_problem v JOIN clinic_app.ehr_historyassessment ha
          ON ha.id=v.assessment_id
        WHERE v.entry_id=NEW.entry_id
        ORDER BY v.version DESC LIMIT 1;
   ELSE
     SELECT v.version,ha.clinic_id,ha.patient_id,ha.encounter_id INTO previous
        FROM clinic_app.ehr_allergy v JOIN clinic_app.ehr_historyassessment ha
          ON ha.id=v.assessment_id
        WHERE v.entry_id=NEW.entry_id
        ORDER BY v.version DESC LIMIT 1;
   END IF;
   IF previous.version IS NULL THEN
     IF NEW.version<>1 THEN
       RAISE EXCEPTION 'invalid initial version' USING ERRCODE='23514';
     END IF;
   ELSIF NEW.version<>previous.version+1
      OR (previous.clinic_id,previous.patient_id)
        IS DISTINCT FROM (h.clinic_id,h.patient_id)
      OR NOT clinic_app.ehr_assigned(previous.encounter_id) THEN
     RAISE EXCEPTION 'invalid predecessor or authority' USING ERRCODE='23514';
   END IF;
 END IF;
 RETURN NEW;
END
$f$;
RESET ROLE;
"""

_DROP_SQL = (
    "".join(
        drop_legacy_sql("ehr_clinicaldocumentversion", column, required=False)
        for column in (*_SOAP_KEYS, "amendment_reason")
    )
    + "".join(
        drop_legacy_sql("ehr_discarded_content", column, required=False)
        for column in _SOAP_KEYS
    )
    + drop_legacy_sql("ehr_historyassessment", "reason", required=True)
    + drop_legacy_sql("ehr_problem", "description", required=True)
    + drop_legacy_sql("ehr_allergy", "description", required=True)
)


def _backfill(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    encrypt_backfill(
        table="ehr_clinicaldocumentversion",
        pk_column="id",
        plans=_VERSION_PLANS,
    )(apps, schema_editor)
    encrypt_backfill(
        table="ehr_discarded_content",
        pk_column="version_id",
        plans=_DISCARDED_PLANS,
    )(apps, schema_editor)
    encrypt_backfill(
        table="ehr_historyassessment",
        pk_column="id",
        plans=_ASSESSMENT_PLANS,
    )(apps, schema_editor)
    encrypt_backfill(table="ehr_problem", pk_column="id", plans=_PROBLEM_PLANS)(
        apps, schema_editor
    )
    encrypt_backfill(table="ehr_allergy", pk_column="id", plans=_ALLERGY_PLANS)(
        apps, schema_editor
    )


def _seal(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    for table, plans in (
        ("ehr_clinicaldocumentversion", _VERSION_PLANS),
        ("ehr_discarded_content", _DISCARDED_PLANS),
        ("ehr_historyassessment", _ASSESSMENT_PLANS),
        ("ehr_problem", _PROBLEM_PLANS),
        ("ehr_allergy", _ALLERGY_PLANS),
    ):
        require_backfill_complete(table=table, plans=plans)(apps, schema_editor)


class Migration(migrations.Migration):
    """Convert clinical protected columns to tenant envelopes."""

    atomic = False
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("ehr", "0008_finalization_policy"),
        ("tenancy", "0004_protected_fields"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_SCHEMA_SQL, reverse_sql=None),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name="clinicaldocumentversion",
                    old_name="subjective",
                    new_name="subjective_legacy",
                ),
                migrations.RenameField(
                    model_name="clinicaldocumentversion",
                    old_name="objective",
                    new_name="objective_legacy",
                ),
                migrations.RenameField(
                    model_name="clinicaldocumentversion",
                    old_name="assessment",
                    new_name="assessment_legacy",
                ),
                migrations.RenameField(
                    model_name="clinicaldocumentversion",
                    old_name="plan",
                    new_name="plan_legacy",
                ),
                migrations.RenameField(
                    model_name="clinicaldocumentversion",
                    old_name="amendment_reason",
                    new_name="amendment_reason_legacy",
                ),
                migrations.RenameField(
                    model_name="historyassessment",
                    old_name="reason",
                    new_name="reason_legacy",
                ),
                migrations.RenameField(
                    model_name="problem",
                    old_name="description",
                    new_name="description_legacy",
                ),
                migrations.RenameField(
                    model_name="allergy",
                    old_name="description",
                    new_name="description_legacy",
                ),
                migrations.AddField(
                    model_name="clinicaldocumentversion",
                    name="content",
                    field=apps.tenancy.fields.EncryptedJSONField(
                        purpose="ehr.clinicaldocumentversion.content",
                        null=True,
                        empty={},
                    ),
                ),
                migrations.AddField(
                    model_name="clinicaldocumentversion",
                    name="content_sha256",
                    field=models.CharField(max_length=64, blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="clinicaldocumentversion",
                    name="amendment_reason",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="ehr.clinicaldocumentversion.amendment_reason",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="historyassessment",
                    name="reason",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="ehr.historyassessment.reason", null=True
                    ),
                ),
                migrations.AddField(
                    model_name="problem",
                    name="description",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="ehr.entryversion.description", null=True
                    ),
                ),
                migrations.AddField(
                    model_name="allergy",
                    name="description",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="ehr.entryversion.description", null=True
                    ),
                ),
            ],
        ),
        migrations.RunPython(code=_backfill, reverse_code=irreversible),
        migrations.RunSQL(sql=_GUARD_SQL, reverse_sql=None),
        migrations.RunPython(code=_seal, reverse_code=irreversible),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_DROP_SQL, reverse_sql=None),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="clinicaldocumentversion",
                    name="subjective_legacy",
                ),
                migrations.RemoveField(
                    model_name="clinicaldocumentversion",
                    name="objective_legacy",
                ),
                migrations.RemoveField(
                    model_name="clinicaldocumentversion",
                    name="assessment_legacy",
                ),
                migrations.RemoveField(
                    model_name="clinicaldocumentversion",
                    name="plan_legacy",
                ),
                migrations.RemoveField(
                    model_name="clinicaldocumentversion",
                    name="amendment_reason_legacy",
                ),
                migrations.RemoveField(
                    model_name="historyassessment", name="reason_legacy"
                ),
                migrations.RemoveField(model_name="problem", name="description_legacy"),
                migrations.RemoveField(model_name="allergy", name="description_legacy"),
                migrations.RemoveConstraint(
                    model_name="clinicaldocumentversion",
                    name="ehr_version_amendment_check",
                ),
                migrations.AddConstraint(
                    model_name="clinicaldocumentversion",
                    constraint=models.CheckConstraint(
                        condition=(
                            models.Q(amendment_of__isnull=True)
                            & models.Q(amendment_reason__isnull=True)
                        )
                        | (
                            models.Q(amendment_of__isnull=False)
                            & models.Q(amendment_reason__isnull=False)
                            & models.Q(version__gte=2)
                        ),
                        name="ehr_version_amendment_check",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="clinicaldocumentversion",
                    constraint=models.CheckConstraint(
                        condition=(
                            models.Q(content__isnull=True, content_sha256="")
                            | (
                                models.Q(content__isnull=False)
                                & models.Q(content_sha256__regex=r"^[0-9a-f]{64}$")
                            )
                        ),
                        name="ehr_version_content_check",
                    ),
                ),
                migrations.RemoveConstraint(
                    model_name="problem",
                    name="problem_description_required",
                ),
                migrations.AddConstraint(
                    model_name="problem",
                    constraint=models.CheckConstraint(
                        condition=models.expressions.RawSQL(
                            "pg_catalog.octet_length(description) > 0",
                            (),
                            output_field=models.BooleanField(),
                        ),
                        name="problem_description_required",
                    ),
                ),
                migrations.RemoveConstraint(
                    model_name="allergy",
                    name="allergy_description_required",
                ),
                migrations.AddConstraint(
                    model_name="allergy",
                    constraint=models.CheckConstraint(
                        condition=models.expressions.RawSQL(
                            "pg_catalog.octet_length(description) > 0",
                            (),
                            output_field=models.BooleanField(),
                        ),
                        name="allergy_description_required",
                    ),
                ),
                migrations.AlterField(
                    model_name="historyassessment",
                    name="reason",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="ehr.historyassessment.reason"
                    ),
                ),
                migrations.AlterField(
                    model_name="problem",
                    name="description",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="ehr.entryversion.description"
                    ),
                ),
                migrations.AlterField(
                    model_name="allergy",
                    name="description",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="ehr.entryversion.description"
                    ),
                ),
            ],
        ),
    ]
