# Generated by hand for the task-43 protected-field integration on 2026-09-22
"""Encrypt the stored PIX copy text and QR payload.

``billing_pixcharge.copy_code`` and ``qr_base64`` are patient-facing payment
instructions; both become tenant-envelope ``bytea`` columns. The PIX guard
can no longer inspect the synthetic prefix on ciphertext, so it enforces the
size bound only - the synthetic adapter still verifies the exact response
contract in Python before the row is written. ``billing_patient_charge``
keeps its resolver predicate but returns the envelopes; the presentation
layer decrypts them under the live patient session. The migration is
irreversible because rollback must never reactivate plaintext storage.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

from django.db import migrations

import apps.tenancy.fields
from apps.tenancy.migrations._protected_migration import (
    drop_legacy_sql,
    encrypt_backfill,
    irreversible,
    rename_to_legacy_sql,
    require_backfill_complete,
)

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


def _encode_text(value: object) -> bytes | None:
    if value is None or value == "":
        return None
    return str(value).encode("utf-8")


_PLANS = (
    (
        "copy_code",
        "billing.pixcharge.copy_code",
        ("copy_code_legacy",),
        (),
        lambda row: _encode_text(row["copy_code_legacy"]),
        None,
    ),
    (
        "qr_base64",
        "billing.pixcharge.qr_base64",
        ("qr_base64_legacy",),
        (),
        lambda row: _encode_text(row["qr_base64_legacy"]),
        None,
    ),
)

_SCHEMA_SQL = (
    rename_to_legacy_sql("billing_pixcharge", "copy_code")
    + rename_to_legacy_sql("billing_pixcharge", "qr_base64")
    + """
ALTER TABLE clinic_app.billing_pixcharge
    ADD COLUMN IF NOT EXISTS copy_code pg_catalog.bytea,
    ADD COLUMN IF NOT EXISTS qr_base64 pg_catalog.bytea;
"""
)

_GUARD_SQL = """
CREATE OR REPLACE FUNCTION clinic_app.billing_pix_guard()
RETURNS trigger LANGUAGE plpgsql
SET search_path = pg_catalog, clinic_app, pg_temp AS $f$
DECLARE
 invoice clinic_app.billing_invoice;
 predecessor clinic_app.billing_pixoperation;
 operation clinic_app.billing_pixoperation;
BEGIN
 IF TG_OP <> 'INSERT' THEN
   RAISE EXCEPTION 'immutable PIX history' USING ERRCODE = '23514';
 END IF;
 SELECT * INTO invoice FROM clinic_app.billing_invoice
 WHERE id = NEW.invoice_id FOR UPDATE;
 IF invoice.id IS NULL OR invoice.organization_id <> NEW.organization_id
    OR invoice.state <> 'open' THEN
   RAISE EXCEPTION 'invalid PIX invoice' USING ERRCODE = '23514';
 END IF;
 IF TG_TABLE_NAME = 'billing_pixoperation' THEN
   IF ROW(NEW.amount_minor, NEW.currency, NEW.invoice_reference)
      IS DISTINCT FROM ROW(invoice.amount_minor, invoice.currency,
                           invoice.reference) THEN
     RAISE EXCEPTION 'invalid PIX terms' USING ERRCODE = '23514';
   END IF;
   IF NEW.previous_id IS NOT NULL THEN
     SELECT * INTO predecessor FROM clinic_app.billing_pixoperation
       WHERE id = NEW.previous_id;
     IF predecessor.id IS NULL OR predecessor.invoice_id <> invoice.id
        OR predecessor.organization_id <> NEW.organization_id
        OR predecessor.expires_at > statement_timestamp() THEN
       RAISE EXCEPTION 'invalid PIX regeneration' USING ERRCODE = '23514';
     END IF;
   END IF;
 ELSE
   SELECT * INTO operation FROM clinic_app.billing_pixoperation
     WHERE id = NEW.operation_id;
   -- copy_code and qr_base64 are tenant envelopes: the synthetic-prefix
   -- contract is verified by the adapter before insert, and the database
   -- enforces presence plus the payload bound on the ciphertext.
   IF operation.id IS NULL OR operation.invoice_id <> invoice.id
      OR operation.organization_id <> NEW.organization_id
      OR NEW.provider_reference <> 'synthetic-pix-' || operation.id::text
      OR NEW.copy_code IS NULL
      OR pg_catalog.octet_length(NEW.qr_base64) NOT BETWEEN 1 AND 131072 THEN
     RAISE EXCEPTION 'invalid synthetic PIX result' USING ERRCODE = '23514';
   END IF;
 END IF;
 RETURN NEW;
END
$f$;
REVOKE ALL ON FUNCTION clinic_app.billing_pix_guard() FROM PUBLIC, clinic_app;

SET LOCAL ROLE clinic_resolver;
DROP FUNCTION clinic_app.billing_patient_charge(uuid);
CREATE FUNCTION clinic_app.billing_patient_charge(requested_invoice uuid)
RETURNS TABLE(invoice_id uuid, reference uuid, amount_minor bigint,
 currency varchar, state varchar, issued_at timestamptz,
 receipt_reference uuid, receipt_issued_at timestamptz,
 copy_code bytea, qr_base64 bytea, expires_at timestamptz, flagged boolean,
 clinic_timezone varchar)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp AS $f$
 SELECT i.id, i.reference, i.amount_minor, i.currency, i.state, i.issued_at,
   r.reference, r.issued_at, pix.copy_code, pix.qr_base64, pix.expires_at,
   COALESCE(pix.flagged, false), clinic.timezone
 FROM clinic_app.billing_invoice i
 JOIN clinic_app.identity_clinic clinic ON clinic.id = i.clinic_id
   AND clinic.organization_id = i.organization_id
 LEFT JOIN clinic_app.billing_receipt r ON r.invoice_id = i.id
 LEFT JOIN LATERAL (
   SELECT c.copy_code, c.qr_base64, o.expires_at,
     EXISTS (SELECT 1 FROM clinic_app.billing_paymentevent e
       WHERE e.operation_id = o.id
       AND e.resolution = 'operator_required') AS flagged
   FROM clinic_app.billing_pixoperation o
   JOIN clinic_app.billing_pixcharge c ON c.operation_id = o.id
   WHERE o.invoice_id = i.id
     AND NOT EXISTS (SELECT 1 FROM clinic_app.billing_pixoperation n
       WHERE n.previous_id = o.id)
   ORDER BY o.created_at DESC, o.id DESC
   LIMIT 1
 ) pix ON true
 WHERE i.id = requested_invoice
   AND i.released_at IS NOT NULL AND i.issued_at IS NOT NULL
   AND EXISTS (SELECT 1 FROM clinic_app.intake_patientsession s
     JOIN clinic_app.intake_patientaccessgrant g ON g.id = s.grant_id
     WHERE s.id =
       NULLIF(current_setting('app.current_patient_session', true), '')::uuid
     AND s.organization_id = i.organization_id AND s.clinic_id = i.clinic_id
     AND s.patient_id = i.patient_id
     AND s.revoked_at IS NULL AND g.revoked_at IS NULL
     AND s.expires_at > statement_timestamp()
     AND s.idle_expires_at > statement_timestamp()
     AND 'billing' = ANY(s.operations))
$f$;
REVOKE ALL ON FUNCTION clinic_app.billing_patient_charge(uuid)
 FROM PUBLIC, clinic_app;
GRANT EXECUTE ON FUNCTION clinic_app.billing_patient_charge(uuid) TO clinic_app;
RESET ROLE;
"""

_DROP_SQL = (
    drop_legacy_sql("billing_pixcharge", "copy_code", required=True)
    + drop_legacy_sql("billing_pixcharge", "qr_base64", required=True)
    + """
ALTER TABLE clinic_app.billing_pixcharge
    ALTER COLUMN copy_code SET NOT NULL,
    ALTER COLUMN qr_base64 SET NOT NULL;
"""
)


class Migration(migrations.Migration):
    """Convert PIX charge payloads to tenant envelopes."""

    atomic = False
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("billing", "0008_invoice_create_idempotency"),
        ("tenancy", "0004_protected_fields"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_SCHEMA_SQL, reverse_sql=None),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name="pixcharge",
                    old_name="copy_code",
                    new_name="copy_code_legacy",
                ),
                migrations.RenameField(
                    model_name="pixcharge",
                    old_name="qr_base64",
                    new_name="qr_base64_legacy",
                ),
                migrations.AddField(
                    model_name="pixcharge",
                    name="copy_code",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="billing.pixcharge.copy_code", null=True
                    ),
                ),
                migrations.AddField(
                    model_name="pixcharge",
                    name="qr_base64",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="billing.pixcharge.qr_base64", null=True
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            code=encrypt_backfill(
                table="billing_pixcharge", pk_column="id", plans=_PLANS
            ),
            reverse_code=irreversible,
        ),
        migrations.RunSQL(sql=_GUARD_SQL, reverse_sql=None),
        migrations.RunPython(
            code=require_backfill_complete(table="billing_pixcharge", plans=_PLANS),
            reverse_code=irreversible,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_DROP_SQL, reverse_sql=None),
            ],
            state_operations=[
                migrations.RemoveField(model_name="pixcharge", name="copy_code_legacy"),
                migrations.RemoveField(model_name="pixcharge", name="qr_base64_legacy"),
                migrations.AlterField(
                    model_name="pixcharge",
                    name="copy_code",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="billing.pixcharge.copy_code"
                    ),
                ),
                migrations.AlterField(
                    model_name="pixcharge",
                    name="qr_base64",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="billing.pixcharge.qr_base64"
                    ),
                ),
            ],
        ),
    ]
