# Generated by Django 5.2.16 on 2026-07-13 01:11
"""Create the initial tenancy domain schema."""

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    """Create the internal tenant probe table."""

    initial = True

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("identity", "0001_initial"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.CreateModel(
            name="TenantProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
