# Generated by hand for the task-43 envelope capability on 2026-09-22
"""Create the wrapped tenant DEK store and the envelope function boundary."""

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.operations.base import Operation

from apps.tenancy.migrations._envelope_sql import INSTALL_SQL, REVERSE_SQL


class Migration(migrations.Migration):
    """Persist wrapped DEK versions behind FORCE RLS and owner functions."""

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("audit", "0002_audit_append"),
        ("identity", "0001_initial"),
        ("tenancy", "0002_rls_and_resolvers"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.CreateModel(
            name="TenantDataKey",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("key_version", models.PositiveIntegerField()),
                ("wrapped_key", models.BinaryField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("retired_at", models.DateTimeField(null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "key_version"),
                        name="tenancy_dek_version_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(status__in=("active", "retired")),
                        name="tenancy_dek_status_check",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(status="active", retired_at__isnull=True)
                            | models.Q(status="retired", retired_at__isnull=False)
                        ),
                        name="tenancy_dek_retirement_check",
                    ),
                ],
            },
        ),
        migrations.RunSQL(sql=INSTALL_SQL, reverse_sql=REVERSE_SQL),
    ]
