# Generated by hand for the task-43 protected-field integration on 2026-09-22
# ruff: noqa: S608 - DDL text built from migration literals, never user input
"""Install context-resolving envelope wrappers and the patient search boundary.

``protected_tenant`` resolves the encryption tenant from the trusted context:
``app.current_tenant`` for staff/owner transactions, or the live
``app.current_patient_session`` row for patient-session transactions (which
never carry a tenant GUC by design). It is resolver-owned so the session read
bypasses RLS exactly like the other session resolvers.

``protected_encrypt``/``protected_decrypt`` are the only field/object
envelope entry points. They bind the resolved tenant into
``app.current_tenant`` for the duration of the call and restore the prior
setting before returning, so a patient-session transaction never retains
staff-style tenant authority. A propagating error aborts the enclosing
subtransaction, which reverts the transaction-local GUC automatically.

``patient_registry_count``/``patient_registry_page`` preserve the approved
search contract (normalized case-insensitive substring, optional exact birth
date, ``lower(name)``/``birth_date``/``patient_id`` ordering, 25-row pages)
by decrypting inside the database boundary: only the authorized page's
plaintext crosses to the application. Both functions re-check the actor's
manager role for the requested clinic inside the current tenant.

``convert_from`` returns text in the C collation (its encoding argument is a
C-collated ``name``), under which ``upper``/``lower`` leave accented letters
unchanged; the decrypted name is therefore re-collated to the database
default so an accented query matches exactly as it did before encryption.
"""

from typing import ClassVar

from django.db import migrations
from django.db.migrations.operations.base import Operation

_TENANT_CHECK: str = """
    IF NOT EXISTS (
        SELECT 1
          FROM clinic_app.identity_userclinicrole AS role_row
          JOIN clinic_app.identity_user AS user_row
            ON user_row.id = role_row.user_id AND user_row.is_active
         WHERE role_row.user_id = NULLIF(
             pg_catalog.current_setting('app.current_user_id', true), ''
         )::pg_catalog.uuid
           AND role_row.organization_id = NULLIF(
               pg_catalog.current_setting('app.current_tenant', true), ''
           )::pg_catalog.uuid
           AND role_row.clinic_id = requested_clinic
           AND role_row.role IN ('owner', 'clinic_admin', 'receptionist')
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '42501',
            MESSAGE = 'clinic manager authority is required';
    END IF;
"""

_DECRYPTED_ROWS: str = """
        SELECT enrollment_row.id AS enrollment_id,
               patient_row.id AS patient_id,
               pg_catalog.convert_from(
                   clinic_app.protected_decrypt(
                       kek, 'intake.patient.full_name', patient_row.full_name
                   ),
                   'UTF8'
               ) COLLATE pg_catalog."default" AS decrypted_name,
               pg_catalog.convert_from(
                   clinic_app.protected_decrypt(
                       kek,
                       'intake.patient.birth_date',
                       patient_row.birth_date
                   ),
                   'UTF8'
               )::pg_catalog.date AS decrypted_birth
          FROM clinic_app.intake_patientclinicenrollment AS enrollment_row
          JOIN clinic_app.intake_patient AS patient_row
            ON patient_row.id = enrollment_row.patient_id
           AND patient_row.organization_id = enrollment_row.organization_id
         WHERE enrollment_row.clinic_id = requested_clinic
           AND enrollment_row.organization_id = NULLIF(
               pg_catalog.current_setting('app.current_tenant', true), ''
           )::pg_catalog.uuid
"""

INSTALL_SQL: str = (
    """
CREATE FUNCTION clinic_app.protected_tenant()
RETURNS pg_catalog.uuid
LANGUAGE plpgsql
STABLE
PARALLEL UNSAFE
SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
DECLARE
    tenant_setting pg_catalog.text;
    session_setting pg_catalog.text;
    resolved pg_catalog.uuid;
BEGIN
    tenant_setting := NULLIF(
        pg_catalog.current_setting('app.current_tenant', true), ''
    );
    IF tenant_setting IS NOT NULL THEN
        IF NOT pg_catalog.pg_input_is_valid(tenant_setting, 'uuid') THEN
            RAISE EXCEPTION USING ERRCODE = '22023',
                MESSAGE = 'valid app.current_tenant is required';
        END IF;
        resolved := tenant_setting::pg_catalog.uuid;
        IF resolved =
            '00000000-0000-0000-0000-000000000000'::pg_catalog.uuid
        THEN
            RAISE EXCEPTION USING ERRCODE = '22023',
                MESSAGE = 'system organization is not a tenant context';
        END IF;
        RETURN resolved;
    END IF;
    session_setting := NULLIF(
        pg_catalog.current_setting('app.current_patient_session', true), ''
    );
    IF session_setting IS NULL
        OR NOT pg_catalog.pg_input_is_valid(session_setting, 'uuid')
    THEN
        RAISE EXCEPTION USING ERRCODE = '22023',
            MESSAGE = 'a tenant or patient session context is required';
    END IF;
    SELECT session_row.organization_id INTO resolved
      FROM clinic_app.intake_patientsession AS session_row
      JOIN clinic_app.intake_patientaccessgrant AS grant_row
        ON grant_row.id = session_row.grant_id
     WHERE session_row.id = session_setting::pg_catalog.uuid
       AND session_row.revoked_at IS NULL
       AND grant_row.revoked_at IS NULL
       AND session_row.expires_at > pg_catalog.statement_timestamp()
       AND session_row.idle_expires_at > pg_catalog.statement_timestamp();
    IF resolved IS NULL THEN
        RAISE EXCEPTION USING ERRCODE = '22023',
            MESSAGE = 'a live patient session context is required';
    END IF;
    RETURN resolved;
END
$function$;

CREATE FUNCTION clinic_app.protected_encrypt(
    kek pg_catalog.text,
    purpose pg_catalog.text,
    plaintext pg_catalog.bytea
)
RETURNS pg_catalog.bytea
LANGUAGE plpgsql
VOLATILE
PARALLEL UNSAFE
SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
DECLARE
    prior_tenant pg_catalog.text;
    resolved pg_catalog.uuid;
    result pg_catalog.bytea;
BEGIN
    resolved := clinic_app.protected_tenant();
    prior_tenant := pg_catalog.current_setting('app.current_tenant', true);
    PERFORM pg_catalog.set_config(
        'app.current_tenant', resolved::pg_catalog.text, true
    );
    result := clinic_app.tenant_encrypt(kek, purpose, plaintext);
    PERFORM pg_catalog.set_config(
        'app.current_tenant', COALESCE(prior_tenant, ''), true
    );
    RETURN result;
END
$function$;

CREATE FUNCTION clinic_app.protected_decrypt(
    kek pg_catalog.text,
    purpose pg_catalog.text,
    envelope pg_catalog.bytea
)
RETURNS pg_catalog.bytea
LANGUAGE plpgsql
STABLE
PARALLEL UNSAFE
SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
DECLARE
    prior_tenant pg_catalog.text;
    resolved pg_catalog.uuid;
    result pg_catalog.bytea;
BEGIN
    resolved := clinic_app.protected_tenant();
    prior_tenant := pg_catalog.current_setting('app.current_tenant', true);
    PERFORM pg_catalog.set_config(
        'app.current_tenant', resolved::pg_catalog.text, true
    );
    result := clinic_app.tenant_decrypt(kek, purpose, envelope);
    PERFORM pg_catalog.set_config(
        'app.current_tenant', COALESCE(prior_tenant, ''), true
    );
    RETURN result;
END
$function$;

CREATE FUNCTION clinic_app.patient_registry_count(
    kek pg_catalog.text,
    requested_clinic pg_catalog.uuid,
    normalized_query pg_catalog.text,
    requested_birth pg_catalog.date
)
RETURNS pg_catalog.int8
LANGUAGE plpgsql
STABLE
PARALLEL UNSAFE
SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
DECLARE
    total pg_catalog.int8;
BEGIN
"""
    + _TENANT_CHECK
    + """
    SELECT pg_catalog.count(*) INTO total
      FROM (
"""
    + _DECRYPTED_ROWS
    + """
      ) AS decrypted
     WHERE pg_catalog.strpos(
         pg_catalog.upper(decrypted.decrypted_name),
         pg_catalog.upper(normalized_query)
     ) > 0
       AND (requested_birth IS NULL
            OR decrypted.decrypted_birth = requested_birth);
    RETURN total;
END
$function$;

CREATE FUNCTION clinic_app.patient_registry_page(
    kek pg_catalog.text,
    requested_clinic pg_catalog.uuid,
    normalized_query pg_catalog.text,
    requested_birth pg_catalog.date,
    page_offset pg_catalog.int4,
    page_limit pg_catalog.int4
)
RETURNS TABLE(
    enrollment_id pg_catalog.uuid,
    full_name pg_catalog.text,
    birth_date pg_catalog.date
)
LANGUAGE plpgsql
STABLE
PARALLEL UNSAFE
SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp
AS $function$
BEGIN
"""
    + _TENANT_CHECK
    + """
    RETURN QUERY
    SELECT decrypted.enrollment_id, decrypted.decrypted_name,
           decrypted.decrypted_birth
      FROM (
"""
    + _DECRYPTED_ROWS
    + """
      ) AS decrypted
     WHERE pg_catalog.strpos(
         pg_catalog.upper(decrypted.decrypted_name),
         pg_catalog.upper(normalized_query)
     ) > 0
       AND (requested_birth IS NULL
            OR decrypted.decrypted_birth = requested_birth)
     ORDER BY pg_catalog.lower(decrypted.decrypted_name),
              decrypted.decrypted_birth,
              decrypted.patient_id
     LIMIT page_limit OFFSET page_offset;
END
$function$;

ALTER FUNCTION clinic_app.protected_tenant() OWNER TO clinic_resolver;
ALTER FUNCTION clinic_app.protected_encrypt(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
) OWNER TO clinic_owner;
ALTER FUNCTION clinic_app.protected_decrypt(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
) OWNER TO clinic_owner;
ALTER FUNCTION clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
) OWNER TO clinic_owner;
ALTER FUNCTION clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
) OWNER TO clinic_owner;

-- ACL changes on resolver-owned functions must run as the resolver: the
-- migration role holds membership with INHERIT FALSE, so revoking or
-- granting as clinic_owner is a silent no-op that leaves PUBLIC EXECUTE.
SET LOCAL ROLE clinic_resolver;
REVOKE ALL ON FUNCTION clinic_app.protected_tenant()
    FROM PUBLIC, clinic_app;
GRANT EXECUTE ON FUNCTION clinic_app.protected_tenant()
    TO clinic_owner;
RESET ROLE;

REVOKE ALL ON FUNCTION clinic_app.protected_encrypt(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
) FROM PUBLIC, clinic_resolver;
REVOKE ALL ON FUNCTION clinic_app.protected_decrypt(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
) FROM PUBLIC, clinic_resolver;
REVOKE ALL ON FUNCTION clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
) FROM PUBLIC, clinic_resolver;
REVOKE ALL ON FUNCTION clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
) FROM PUBLIC, clinic_resolver;

GRANT EXECUTE ON FUNCTION clinic_app.protected_encrypt(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
) TO clinic_app;
GRANT EXECUTE ON FUNCTION clinic_app.protected_decrypt(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
) TO clinic_app;
GRANT EXECUTE ON FUNCTION clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
) TO clinic_app;
GRANT EXECUTE ON FUNCTION clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
) TO clinic_app;
"""
)

REVERSE_SQL: str = """
DROP FUNCTION IF EXISTS clinic_app.patient_registry_page(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date,
    pg_catalog.int4, pg_catalog.int4
);
DROP FUNCTION IF EXISTS clinic_app.patient_registry_count(
    pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.date
);
DROP FUNCTION IF EXISTS clinic_app.protected_decrypt(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
);
DROP FUNCTION IF EXISTS clinic_app.protected_encrypt(
    pg_catalog.text, pg_catalog.text, pg_catalog.bytea
);
DROP FUNCTION IF EXISTS clinic_app.protected_tenant();
"""


class Migration(migrations.Migration):
    """Install the context-resolving envelope boundary and search functions."""

    dependencies: ClassVar[list[tuple[str, str]]] = [
        (
            "intake",
            "0010_remove_patientaccessgrant_intake_grant_operations_check_and_more",
        ),
        ("tenancy", "0003_tenant_envelope"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.RunSQL(sql=INSTALL_SQL, reverse_sql=REVERSE_SQL),
    ]
