# Generated by hand for the task-43 protected-field integration on 2026-09-22
"""Encrypt prescription item text.

All eight ``prescription_prescriptionitem`` text columns become
tenant-envelope ``bytea`` columns. The item guard can no longer trim
ciphertext, so it enforces presence (a blank value encodes to NULL); the
service layer's ``validate_items`` remains the non-blank authority and runs
before every write. ``prescription_prescriptiondocument.pdf_bytes`` /
``frozen_input`` and ``signatureoperation.signed_bytes`` migrate in
``0010_protected_documents``: the anonymous verification resolver decrypts
inside its own boundary through ``prescription_document_open``.
The migration is irreversible because rollback must never reactivate
plaintext storage.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

from django.db import migrations

import apps.tenancy.fields
from apps.tenancy.migrations._protected_migration import (
    drop_legacy_sql,
    encrypt_backfill,
    irreversible,
    rename_to_legacy_sql,
    require_backfill_complete,
)

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation

    from apps.tenancy.migrations._protected_migration import ProtectedPlan

_ITEM_FIELDS = (
    "medication_description",
    "strength_form",
    "dose",
    "route",
    "frequency",
    "duration",
    "quantity",
    "instructions",
)
_REQUIRED_ITEM_FIELDS = _ITEM_FIELDS[:-1]


def _encode_text(value: object) -> bytes | None:
    if value is None or value == "":
        return None
    return str(value).encode("utf-8")


def _plan(field: str) -> ProtectedPlan:
    return (
        field,
        f"prescription.prescriptionitem.{field}",
        (f"{field}_legacy",),
        (),
        lambda row, name=field: _encode_text(row[f"{name}_legacy"]),
        None,
    )


_PLANS = tuple(_plan(field) for field in _ITEM_FIELDS)

_SCHEMA_SQL = (
    "".join(
        rename_to_legacy_sql("prescription_prescriptionitem", field)
        for field in _ITEM_FIELDS
    )
    + "ALTER TABLE clinic_app.prescription_prescriptionitem\n    "
    + ",\n    ".join(
        f"ADD COLUMN IF NOT EXISTS {field} pg_catalog.bytea" for field in _ITEM_FIELDS
    )
    + ";\n"
)

_GUARD_SQL = """
SET LOCAL ROLE clinic_resolver;
CREATE OR REPLACE FUNCTION clinic_app.prescription_item_guard()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp AS $f$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM clinic_app.prescription_prescriptiondraft d
   WHERE d.id=NEW.draft_id AND d.organization_id=NEW.organization_id
     AND d.version=NEW.version AND d.state='draft')
   OR NEW.medication_description IS NULL OR NEW.strength_form IS NULL
   OR NEW.dose IS NULL OR NEW.route IS NULL OR NEW.frequency IS NULL
   OR NEW.duration IS NULL OR NEW.quantity IS NULL THEN
   RAISE EXCEPTION 'invalid prescription item binding' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END $f$;
RESET ROLE;
"""

_DROP_SQL = (
    "".join(
        drop_legacy_sql(
            "prescription_prescriptionitem",
            field,
            required=field in _REQUIRED_ITEM_FIELDS,
        )
        for field in _ITEM_FIELDS
    )
    + "ALTER TABLE clinic_app.prescription_prescriptionitem\n    "
    + ",\n    ".join(
        f"ALTER COLUMN {field} SET NOT NULL" for field in _REQUIRED_ITEM_FIELDS
    )
    + ";\n"
)


class Migration(migrations.Migration):
    """Convert prescription item text to tenant envelopes."""

    atomic = False
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("prescription", "0008_verification_policy"),
        ("tenancy", "0004_protected_fields"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_SCHEMA_SQL, reverse_sql=None),
            ],
            state_operations=[
                *(
                    migrations.RenameField(
                        model_name="prescriptionitem",
                        old_name=field,
                        new_name=f"{field}_legacy",
                    )
                    for field in _ITEM_FIELDS
                ),
                *(
                    migrations.AddField(
                        model_name="prescriptionitem",
                        name=field,
                        field=apps.tenancy.fields.EncryptedTextField(
                            purpose=f"prescription.prescriptionitem.{field}",
                            null=True,
                        ),
                    )
                    for field in _ITEM_FIELDS
                ),
            ],
        ),
        migrations.RunPython(
            code=encrypt_backfill(
                table="prescription_prescriptionitem",
                pk_column="id",
                plans=_PLANS,
            ),
            reverse_code=irreversible,
        ),
        migrations.RunSQL(sql=_GUARD_SQL, reverse_sql=None),
        migrations.RunPython(
            code=require_backfill_complete(
                table="prescription_prescriptionitem", plans=_PLANS
            ),
            reverse_code=irreversible,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_DROP_SQL, reverse_sql=None),
            ],
            state_operations=[
                *(
                    migrations.RemoveField(
                        model_name="prescriptionitem",
                        name=f"{field}_legacy",
                    )
                    for field in _ITEM_FIELDS
                ),
                *(
                    migrations.AlterField(
                        model_name="prescriptionitem",
                        name=field,
                        field=apps.tenancy.fields.EncryptedTextField(
                            purpose=f"prescription.prescriptionitem.{field}"
                        ),
                    )
                    for field in _REQUIRED_ITEM_FIELDS
                ),
            ],
        ),
    ]
