# Generated by hand for the task-43 protected-field integration on 2026-09-22
"""Encrypt prescription document bytes and the frozen input snapshot.

``prescription_prescriptiondocument.pdf_bytes``/``frozen_input`` and
``prescription_signatureoperation.signed_bytes`` become tenant-envelope
``bytea`` columns. The anonymous verification resolver can no longer read
plaintext, so ``prescription_verify`` and the patient document resolvers
take the KEK as a parameter and decrypt inside the resolver boundary
through ``clinic_app.prescription_document_open``, which binds
``app.current_tenant`` to the row's own organization for the duration of
the call. ``clinic_resolver`` receives EXECUTE on ``tenant_decrypt`` for
exactly this purpose; the runtime role's grants are unchanged.

The document guard can no longer inspect plaintext, so the PDF magic and
frozen-input shape checks move to the service layer (which already
validates rendered bytes and digests before insert); the trigger keeps the
binding, digest-format and ciphertext-bound checks. Backfill verifies each
envelope's plaintext digest against the stored ``pdf_digest``/
``signed_digest`` and recomputes ``input_digest`` from the canonical
frozen input before encrypting, so a drifted legacy row fails the
migration instead of sealing a lie. The migration is irreversible because
rollback must never reactivate plaintext storage.
"""

from __future__ import annotations

import hashlib
import json
from typing import TYPE_CHECKING, ClassVar

import rfc8785
from django.db import migrations

import apps.tenancy.fields
from apps.tenancy.migrations._protected_migration import (
    ProtectedRow,
    drop_legacy_sql,
    encrypt_backfill,
    irreversible,
    rename_to_legacy_sql,
    require_backfill_complete,
)

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.operations.base import Operation

# 2 MiB plaintext bound plus envelope framing overhead.
_MAX_DOCUMENT_ENVELOPE_BYTES = 2162688
_PDF_DIGEST_ERROR = "prescription_prescriptiondocument.pdf_bytes digest mismatch"
_FROZEN_SHAPE_ERROR = "prescription_prescriptiondocument.frozen_input is not an object"
_FROZEN_DIGEST_ERROR = "prescription_prescriptiondocument.frozen_input digest mismatch"
_SIGNED_DIGEST_ERROR = "prescription_signatureoperation.signed_bytes digest mismatch"


def _encode_pdf(row: ProtectedRow) -> bytes | None:
    """Encrypt the rendered bytes only when the stored digest still holds."""
    plaintext = row["pdf_bytes_legacy"]
    if plaintext is None:
        return None
    data = bytes(plaintext)
    if hashlib.sha256(data).hexdigest() != row["pdf_digest"]:
        raise RuntimeError(_PDF_DIGEST_ERROR)
    return data


def _encode_frozen_input(row: ProtectedRow) -> bytes | None:
    """Encrypt the canonical frozen input only when its digest still holds.

    The raw migration cursor returns JSONB as its text representation, so a
    ``str`` is parsed back to the logical value before the shape and digest
    checks — the column's type is JSON, not the cursor's wire form.
    """
    value = row["frozen_input_legacy"]
    if value is None:
        return None
    if isinstance(value, str):
        value = json.loads(value)
    if not isinstance(value, dict):
        raise TypeError(_FROZEN_SHAPE_ERROR)
    content = {key: item for key, item in value.items() if key != "input_digest"}
    if hashlib.sha256(rfc8785.dumps(content)).hexdigest() != row["input_digest"]:
        raise RuntimeError(_FROZEN_DIGEST_ERROR)
    return rfc8785.dumps(value)


def _encode_signed(row: ProtectedRow) -> bytes | None:
    """Encrypt signed bytes only when the stored digest still holds."""
    plaintext = row["signed_bytes_legacy"]
    if plaintext is None:
        return None
    data = bytes(plaintext)
    if hashlib.sha256(data).hexdigest() != row["signed_digest"]:
        raise RuntimeError(_SIGNED_DIGEST_ERROR)
    return data


_DOCUMENT_PLANS = (
    (
        "pdf_bytes",
        "prescription.prescriptiondocument.pdf_bytes",
        ("pdf_bytes_legacy",),
        ("pdf_digest",),
        _encode_pdf,
        None,
    ),
    (
        "frozen_input",
        "prescription.prescriptiondocument.frozen_input",
        ("frozen_input_legacy",),
        ("input_digest",),
        _encode_frozen_input,
        None,
    ),
)
_OPERATION_PLANS = (
    (
        "signed_bytes",
        "prescription.signatureoperation.signed_bytes",
        ("signed_bytes_legacy",),
        ("signed_digest",),
        _encode_signed,
        None,
    ),
)

_SCHEMA_SQL = (
    rename_to_legacy_sql("prescription_prescriptiondocument", "pdf_bytes")
    + rename_to_legacy_sql("prescription_prescriptiondocument", "frozen_input")
    + rename_to_legacy_sql("prescription_signatureoperation", "signed_bytes")
    + """
-- The column-level UPDATE grant followed the renamed legacy column; the
-- signing callback writes the new envelope column and needs its own grant.
-- The document table carries table-level SELECT/INSERT grants, which already
-- cover columns added later.
GRANT UPDATE (signed_bytes)
    ON clinic_app.prescription_signatureoperation TO clinic_app;
"""
)

_GUARD_SQL = f"""
SET LOCAL ROLE clinic_resolver;
CREATE OR REPLACE FUNCTION clinic_app.prescription_document_guard()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp AS $f$
DECLARE d clinic_app.prescription_prescriptiondraft;
BEGIN
 SELECT * INTO d FROM clinic_app.prescription_prescriptiondraft
  WHERE id = NEW.draft_id;
 IF d.id IS NULL OR d.state <> 'draft'
    OR (d.organization_id,d.clinic_id,d.encounter_id,d.patient_id,d.issuer_id)
       IS DISTINCT FROM
       (NEW.organization_id,NEW.clinic_id,NEW.encounter_id,NEW.patient_id,
        NEW.issuer_id)
    OR NEW.document_version <> d.version THEN
   RAISE EXCEPTION 'invalid prescription document binding' USING ERRCODE='23514';
 END IF;
 -- pdf_bytes and frozen_input are tenant envelopes: the PDF magic and
 -- JSON shape checks live in the render service, which validates the exact
 -- plaintext and both digests before the row exists.
 IF NEW.state <> 'rendered'
    OR NEW.input_digest !~ '^[0-9a-f]{{64}}$'
    OR NEW.pdf_digest !~ '^[0-9a-f]{{64}}$'
    OR NEW.qr_handle !~ '^[A-Za-z0-9_-]{{32,64}}$'
    OR NEW.pdf_bytes IS NULL
    OR pg_catalog.octet_length(NEW.pdf_bytes) > {_MAX_DOCUMENT_ENVELOPE_BYTES}
    OR NEW.frozen_input IS NULL
    OR pg_catalog.jsonb_typeof(NEW.render_params) <> 'object' THEN
   RAISE EXCEPTION 'invalid prescription document content' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END $f$;
RESET ROLE;
"""  # noqa: S608 - DDL text built from migration literals

_RESOLVER_SQL = """
-- The resolver decrypts inside its own boundary: the KEK arrives per call
-- from the application secret store, and prescription_document_open binds
-- app.current_tenant to the row's organization for the decrypt call only.
GRANT EXECUTE ON FUNCTION clinic_app.tenant_decrypt(
  pg_catalog.text, pg_catalog.text, pg_catalog.bytea) TO clinic_resolver;
SET LOCAL ROLE clinic_resolver;
CREATE FUNCTION clinic_app.prescription_document_open(
 kek pg_catalog.text,
 organization_id pg_catalog.uuid,
 purpose pg_catalog.text,
 envelope pg_catalog.bytea
)
RETURNS pg_catalog.bytea
LANGUAGE plpgsql STABLE PARALLEL UNSAFE SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp AS $f$
DECLARE
 prior_tenant pg_catalog.text;
BEGIN
 prior_tenant := pg_catalog.current_setting('app.current_tenant', true);
 PERFORM pg_catalog.set_config(
   'app.current_tenant', organization_id::pg_catalog.text, true);
 BEGIN
   RETURN clinic_app.tenant_decrypt(kek, purpose, envelope);
 EXCEPTION WHEN OTHERS THEN
   PERFORM pg_catalog.set_config(
     'app.current_tenant', COALESCE(prior_tenant, ''), true);
   RAISE;
 END;
END
$f$;
DROP FUNCTION clinic_app.prescription_verify(pg_catalog.text, pg_catalog.bool);
CREATE FUNCTION clinic_app.prescription_verify(
 kek pg_catalog.text,
 requested_handle pg_catalog.text,
 allow_synthetic pg_catalog.bool
)
RETURNS TABLE(
 status pg_catalog.text,
 document_version pg_catalog.int4,
 issued_at pg_catalog.timestamptz,
 content_digest pg_catalog.text,
 signed_digest pg_catalog.text,
 issuer_label pg_catalog.text,
 clinic_label pg_catalog.text
)
LANGUAGE plpgsql STABLE PARALLEL UNSAFE SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp AS $f$
DECLARE
 d clinic_app.prescription_prescriptiondocument;
 o clinic_app.prescription_signatureoperation;
 pdf_plain pg_catalog.bytea;
 signed_plain pg_catalog.bytea;
 frozen_plain pg_catalog.bytea;
 frozen pg_catalog.jsonb;
BEGIN
 -- Unknown, malformed and unissued handles are indistinguishable.
 IF requested_handle IS NULL
    OR pg_catalog.char_length(requested_handle) < 32
    OR pg_catalog.char_length(requested_handle) > 64
    OR requested_handle !~ '^[A-Za-z0-9_-]+$' THEN
   RETURN QUERY SELECT 'unavailable'::pg_catalog.text,
     NULL::pg_catalog.int4, NULL::pg_catalog.timestamptz,
     NULL::pg_catalog.text, NULL::pg_catalog.text,
     NULL::pg_catalog.text, NULL::pg_catalog.text;
   RETURN;
 END IF;
 SELECT * INTO d FROM clinic_app.prescription_prescriptiondocument
  WHERE qr_handle = requested_handle;
 IF d.id IS NULL THEN
   RETURN QUERY SELECT 'unavailable'::pg_catalog.text,
     NULL::pg_catalog.int4, NULL::pg_catalog.timestamptz,
     NULL::pg_catalog.text, NULL::pg_catalog.text,
     NULL::pg_catalog.text, NULL::pg_catalog.text;
   RETURN;
 END IF;
 -- Decrypt inside the boundary; a missing key is unavailable, any other
 -- envelope or plaintext failure is indistinguishable from tampering.
 BEGIN
   pdf_plain := clinic_app.prescription_document_open(
     kek, d.organization_id,
     'prescription.prescriptiondocument.pdf_bytes', d.pdf_bytes);
 EXCEPTION
   WHEN OTHERS THEN
     IF SQLSTATE = 'TEN01' THEN
       RETURN QUERY SELECT 'unavailable'::pg_catalog.text,
         NULL::pg_catalog.int4, NULL::pg_catalog.timestamptz,
         NULL::pg_catalog.text, NULL::pg_catalog.text,
         NULL::pg_catalog.text, NULL::pg_catalog.text;
     ELSE
       RETURN QUERY SELECT 'invalid'::pg_catalog.text, d.document_version,
         NULL::pg_catalog.timestamptz,
         NULL::pg_catalog.text, NULL::pg_catalog.text,
         NULL::pg_catalog.text, NULL::pg_catalog.text;
     END IF;
     RETURN;
 END;
 -- Stored bytes that no longer match their recorded digests can never
 -- verify as anything but invalid; the status is still published.
 IF pg_catalog.encode(
      clinic_app.digest(pdf_plain, 'sha256'), 'hex') <> d.pdf_digest THEN
   RETURN QUERY SELECT 'invalid'::pg_catalog.text, d.document_version,
     NULL::pg_catalog.timestamptz,
     NULL::pg_catalog.text, NULL::pg_catalog.text,
     NULL::pg_catalog.text, NULL::pg_catalog.text;
   RETURN;
 END IF;
 SELECT * INTO o FROM clinic_app.prescription_signatureoperation op
  WHERE op.document_id = d.id
    AND op.state IN ('issued', 'rehearsal_complete')
  ORDER BY op.completed_at DESC, op.id LIMIT 1;
 IF o.id IS NULL THEN
   RETURN QUERY SELECT 'unavailable'::pg_catalog.text,
     NULL::pg_catalog.int4, NULL::pg_catalog.timestamptz,
     NULL::pg_catalog.text, NULL::pg_catalog.text,
     NULL::pg_catalog.text, NULL::pg_catalog.text;
   RETURN;
 END IF;
 BEGIN
   signed_plain := clinic_app.prescription_document_open(
     kek, o.organization_id,
     'prescription.signatureoperation.signed_bytes', o.signed_bytes);
   frozen_plain := clinic_app.prescription_document_open(
     kek, d.organization_id,
     'prescription.prescriptiondocument.frozen_input', d.frozen_input);
 EXCEPTION
   WHEN OTHERS THEN
     IF SQLSTATE = 'TEN01' THEN
       RETURN QUERY SELECT 'unavailable'::pg_catalog.text,
         NULL::pg_catalog.int4, NULL::pg_catalog.timestamptz,
         NULL::pg_catalog.text, NULL::pg_catalog.text,
         NULL::pg_catalog.text, NULL::pg_catalog.text;
     ELSE
       RETURN QUERY SELECT 'invalid'::pg_catalog.text, d.document_version,
         NULL::pg_catalog.timestamptz,
         NULL::pg_catalog.text, NULL::pg_catalog.text,
         NULL::pg_catalog.text, NULL::pg_catalog.text;
     END IF;
     RETURN;
 END;
 frozen := pg_catalog.convert_from(frozen_plain, 'UTF8')::pg_catalog.jsonb;
 IF pg_catalog.encode(
      clinic_app.digest(signed_plain, 'sha256'), 'hex')
    <> o.signed_digest THEN
   RETURN QUERY SELECT 'invalid'::pg_catalog.text, d.document_version,
     NULL::pg_catalog.timestamptz,
     NULL::pg_catalog.text, NULL::pg_catalog.text,
     NULL::pg_catalog.text, NULL::pg_catalog.text;
   RETURN;
 END IF;
 IF EXISTS (SELECT 1
    FROM clinic_app.prescription_prescriptiondocumentrevocation rv
    WHERE rv.document_id = d.id) THEN
   RETURN QUERY SELECT 'revoked'::pg_catalog.text, d.document_version,
     o.completed_at, d.pdf_digest::pg_catalog.text,
     o.signed_digest::pg_catalog.text,
     (frozen->>'issuer_label')::pg_catalog.text,
     (frozen->>'clinic_label')::pg_catalog.text;
   RETURN;
 END IF;
 IF EXISTS (SELECT 1
    FROM clinic_app.prescription_prescriptiondocument newer
    WHERE newer.draft_id = d.draft_id
      AND newer.document_version > d.document_version
      AND EXISTS (SELECT 1
        FROM clinic_app.prescription_signatureoperation newer_op
        WHERE newer_op.document_id = newer.id
          AND newer_op.state IN ('issued', 'rehearsal_complete'))) THEN
   RETURN QUERY SELECT 'superseded'::pg_catalog.text, d.document_version,
     o.completed_at, d.pdf_digest::pg_catalog.text,
     o.signed_digest::pg_catalog.text,
     (frozen->>'issuer_label')::pg_catalog.text,
     (frozen->>'clinic_label')::pg_catalog.text;
   RETURN;
 END IF;
 -- The signature is verified inside this privileged boundary; only the
 -- verdict is published. Signed bytes never leave the resolver, so the
 -- public handle can never grant document access. A disabled or unknown
 -- provider reports unavailable, never a false valid status.
 IF o.provider <> 'synthetic-signature-v1'
    OR allow_synthetic IS NOT TRUE THEN
   RETURN QUERY SELECT 'unavailable'::pg_catalog.text,
     NULL::pg_catalog.int4, NULL::pg_catalog.timestamptz,
     NULL::pg_catalog.text, NULL::pg_catalog.text,
     NULL::pg_catalog.text, NULL::pg_catalog.text;
   RETURN;
 END IF;
 IF NOT clinic_app.prescription_verify_synthetic(
   signed_plain, d.pdf_digest, o.signer_subject,
   o.operation_id, o.created_at) THEN
   RETURN QUERY SELECT 'invalid'::pg_catalog.text, d.document_version,
     NULL::pg_catalog.timestamptz,
     NULL::pg_catalog.text, NULL::pg_catalog.text,
     NULL::pg_catalog.text, NULL::pg_catalog.text;
   RETURN;
 END IF;
 RETURN QUERY SELECT o.state::pg_catalog.text, d.document_version,
   o.completed_at, d.pdf_digest::pg_catalog.text,
   o.signed_digest::pg_catalog.text,
   (frozen->>'issuer_label')::pg_catalog.text,
   (frozen->>'clinic_label')::pg_catalog.text;
END
$f$;
DROP FUNCTION clinic_app.prescription_patient_documents();
-- The release authority itself needs no key: it is the same session-scoped
-- predicate with the encrypted projection removed. ``prescription_document_viewed``
-- keeps calling this zero-argument form to authorize the download event,
-- so no audit path ever has to carry a KEK.
CREATE FUNCTION clinic_app.prescription_patient_documents()
RETURNS TABLE(document_id pg_catalog.uuid,
              document_version pg_catalog.int4,
              state pg_catalog.text,
              issued_at pg_catalog.timestamptz)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp AS $f$
 SELECT d.id, d.document_version, o.state::pg_catalog.text, o.completed_at
   FROM clinic_app.prescription_prescriptiondocumentrelease r
   JOIN clinic_app.prescription_prescriptiondocument d
     ON d.id = r.document_id
   JOIN clinic_app.prescription_signatureoperation o
     ON o.document_id = d.id
     AND o.state IN ('issued', 'rehearsal_complete')
   WHERE r.revoked_at IS NULL
   AND NOT EXISTS (SELECT 1
     FROM clinic_app.prescription_prescriptiondocumentrevocation rv
     WHERE rv.document_id = d.id)
   AND EXISTS (SELECT 1 FROM clinic_app.retention_records_session() s
     WHERE s.organization_id = r.organization_id
     AND s.clinic_id = r.clinic_id AND s.patient_id = r.patient_id)
   ORDER BY d.document_version, d.id
$f$;
CREATE FUNCTION clinic_app.prescription_patient_documents(
 kek pg_catalog.text
)
RETURNS TABLE(document_id pg_catalog.uuid,
              document_version pg_catalog.int4,
              state pg_catalog.text,
              issued_at pg_catalog.timestamptz,
              verification_url pg_catalog.text)
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp AS $f$
DECLARE
 release_row RECORD;
 frozen_plain pg_catalog.bytea;
BEGIN
 FOR release_row IN
   SELECT d.id, d.document_version, o.state::pg_catalog.text AS op_state,
     o.completed_at, d.frozen_input, d.organization_id
   FROM clinic_app.prescription_prescriptiondocumentrelease r
   JOIN clinic_app.prescription_prescriptiondocument d
     ON d.id = r.document_id
   JOIN clinic_app.prescription_signatureoperation o
     ON o.document_id = d.id
     AND o.state IN ('issued', 'rehearsal_complete')
   WHERE r.revoked_at IS NULL
   AND NOT EXISTS (SELECT 1
     FROM clinic_app.prescription_prescriptiondocumentrevocation rv
     WHERE rv.document_id = d.id)
   AND EXISTS (SELECT 1 FROM clinic_app.retention_records_session() s
     WHERE s.organization_id = r.organization_id
     AND s.clinic_id = r.clinic_id AND s.patient_id = r.patient_id)
   ORDER BY d.document_version, d.id
 LOOP
   frozen_plain := clinic_app.prescription_document_open(
     kek, release_row.organization_id,
     'prescription.prescriptiondocument.frozen_input',
     release_row.frozen_input);
   document_id := release_row.id;
   document_version := release_row.document_version;
   state := release_row.op_state;
   issued_at := release_row.completed_at;
   verification_url := pg_catalog.convert_from(frozen_plain, 'UTF8')
     ::pg_catalog.jsonb->>'verification_url';
   RETURN NEXT;
 END LOOP;
 RETURN;
END
$f$;
DROP FUNCTION clinic_app.prescription_patient_document_bytes(
 pg_catalog.uuid);
CREATE FUNCTION clinic_app.prescription_patient_document_bytes(
 kek pg_catalog.text,
 requested_document pg_catalog.uuid
)
RETURNS pg_catalog.bytea
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp AS $f$
DECLARE
 o clinic_app.prescription_signatureoperation;
 signed_plain pg_catalog.bytea;
BEGIN
 -- NULL for every failure: unknown, unreleased, revoked, unsigned and
 -- digest-mismatched documents are indistinguishable to the patient.
 SELECT op.* INTO o
   FROM clinic_app.prescription_prescriptiondocumentrelease r
   JOIN clinic_app.prescription_prescriptiondocument d
     ON d.id = r.document_id
   JOIN clinic_app.prescription_signatureoperation op
     ON op.document_id = d.id
     AND op.state IN ('issued', 'rehearsal_complete')
   WHERE r.document_id = requested_document
   AND r.revoked_at IS NULL
   AND NOT EXISTS (SELECT 1
     FROM clinic_app.prescription_prescriptiondocumentrevocation rv
     WHERE rv.document_id = d.id)
   AND EXISTS (SELECT 1 FROM clinic_app.retention_records_session() s
     WHERE s.organization_id = r.organization_id
     AND s.clinic_id = r.clinic_id AND s.patient_id = r.patient_id);
 IF o.id IS NULL OR o.signed_bytes IS NULL THEN
   RETURN NULL;
 END IF;
 signed_plain := clinic_app.prescription_document_open(
   kek, o.organization_id,
   'prescription.signatureoperation.signed_bytes', o.signed_bytes);
 IF pg_catalog.encode(
   clinic_app.digest(signed_plain, 'sha256'), 'hex') <> o.signed_digest THEN
   RETURN NULL;
 END IF;
 RETURN signed_plain;
END
$f$;
REVOKE ALL ON FUNCTION clinic_app.prescription_document_open(
  pg_catalog.text, pg_catalog.uuid, pg_catalog.text, pg_catalog.bytea),
 clinic_app.prescription_verify(
  pg_catalog.text, pg_catalog.text, pg_catalog.bool),
 clinic_app.prescription_patient_documents(),
 clinic_app.prescription_patient_documents(pg_catalog.text),
 clinic_app.prescription_patient_document_bytes(
  pg_catalog.text, pg_catalog.uuid)
 FROM PUBLIC;
GRANT EXECUTE ON FUNCTION clinic_app.prescription_verify(
  pg_catalog.text, pg_catalog.text, pg_catalog.bool),
 clinic_app.prescription_patient_documents(),
 clinic_app.prescription_patient_documents(pg_catalog.text),
 clinic_app.prescription_patient_document_bytes(
  pg_catalog.text, pg_catalog.uuid)
 TO clinic_app;
GRANT EXECUTE ON FUNCTION clinic_app.prescription_patient_documents(),
 clinic_app.prescription_patient_documents(pg_catalog.text),
 clinic_app.prescription_patient_document_bytes(
  pg_catalog.text, pg_catalog.uuid)
 TO clinic_owner;
RESET ROLE;
"""

_DROP_SQL = (
    drop_legacy_sql("prescription_prescriptiondocument", "pdf_bytes", required=True)
    + drop_legacy_sql(
        "prescription_prescriptiondocument", "frozen_input", required=True
    )
    + drop_legacy_sql("prescription_signatureoperation", "signed_bytes", required=False)
    + """
ALTER TABLE clinic_app.prescription_prescriptiondocument
    ALTER COLUMN pdf_bytes SET NOT NULL,
    ALTER COLUMN frozen_input SET NOT NULL;
"""
)


def _backfill(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    encrypt_backfill(
        table="prescription_prescriptiondocument",
        pk_column="id",
        plans=_DOCUMENT_PLANS,
    )(apps, schema_editor)
    encrypt_backfill(
        table="prescription_signatureoperation",
        pk_column="id",
        plans=_OPERATION_PLANS,
    )(apps, schema_editor)


def _seal(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    for table, plans in (
        ("prescription_prescriptiondocument", _DOCUMENT_PLANS),
        ("prescription_signatureoperation", _OPERATION_PLANS),
    ):
        require_backfill_complete(table=table, plans=plans)(apps, schema_editor)


class Migration(migrations.Migration):
    """Convert prescription document payloads to tenant envelopes."""

    atomic = False
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("prescription", "0009_protected_fields"),
        ("tenancy", "0004_protected_fields"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_SCHEMA_SQL, reverse_sql=None),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name="prescriptiondocument",
                    old_name="pdf_bytes",
                    new_name="pdf_bytes_legacy",
                ),
                migrations.RenameField(
                    model_name="prescriptiondocument",
                    old_name="frozen_input",
                    new_name="frozen_input_legacy",
                ),
                migrations.RenameField(
                    model_name="signatureoperation",
                    old_name="signed_bytes",
                    new_name="signed_bytes_legacy",
                ),
                migrations.AddField(
                    model_name="prescriptiondocument",
                    name="pdf_bytes",
                    field=apps.tenancy.fields.EncryptedBytesField(
                        purpose="prescription.prescriptiondocument.pdf_bytes",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="prescriptiondocument",
                    name="frozen_input",
                    field=apps.tenancy.fields.EncryptedJSONField(
                        purpose="prescription.prescriptiondocument.frozen_input",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="signatureoperation",
                    name="signed_bytes",
                    field=apps.tenancy.fields.EncryptedBytesField(
                        purpose="prescription.signatureoperation.signed_bytes",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RunPython(code=_backfill, reverse_code=irreversible),
        migrations.RunSQL(sql=_GUARD_SQL, reverse_sql=None),
        migrations.RunSQL(sql=_RESOLVER_SQL, reverse_sql=None),
        migrations.RunPython(code=_seal, reverse_code=irreversible),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_DROP_SQL, reverse_sql=None),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="prescriptiondocument",
                    name="pdf_bytes_legacy",
                ),
                migrations.RemoveField(
                    model_name="prescriptiondocument",
                    name="frozen_input_legacy",
                ),
                migrations.RemoveField(
                    model_name="signatureoperation",
                    name="signed_bytes_legacy",
                ),
                migrations.AlterField(
                    model_name="prescriptiondocument",
                    name="pdf_bytes",
                    field=apps.tenancy.fields.EncryptedBytesField(
                        purpose="prescription.prescriptiondocument.pdf_bytes"
                    ),
                ),
                migrations.AlterField(
                    model_name="prescriptiondocument",
                    name="frozen_input",
                    field=apps.tenancy.fields.EncryptedJSONField(
                        purpose="prescription.prescriptiondocument.frozen_input"
                    ),
                ),
            ],
        ),
    ]
