# Generated by Django 5.2.17 on 2026-09-28 16:05, hand-edited for posture SQL
"""Teleconsult v2: provider-version rooms, device checks and participant events.

Additive: the new room columns default to empty for rooms stored before this
migration, while the rewritten insert trigger requires them for new rooms.
Rooms name their ``video`` capability version by natural identity (provider,
environment) because recovery re-seeds the registry under fresh surrogate
keys. The synthetic video capability version is seeded so synthetic rooms
can bind to it; the reverse keeps that registry row (registry history is never
deleted) and restores the exact v1 binding guard.
"""

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.operations.base import Operation

from ._provider_seed import seed_synthetic_video_version
from ._teleconsult_v2_sql import REVERSE_SQL, SQL


def _seed(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    del schema_editor
    seed_synthetic_video_version(apps)


class Migration(migrations.Migration):
    """Bind rooms to provider versions; add device checks and v2 events."""

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("comms", "0005_operation_state_counts"),
        ("identity", "0013_permission_bundles"),
        ("teleconsult", "0003_teleconsult_fail"),
        ("intake", "0011_protected_fields"),
        ("providers", "0001_initial"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.CreateModel(
            name="TeleconsultDeviceCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("physician", "Médico"), ("patient", "Paciente")],
                        max_length=16,
                    ),
                ),
                ("participant_id", models.UUIDField()),
                ("camera", models.CharField(max_length=16)),
                ("microphone", models.CharField(max_length=16)),
                ("speaker", models.CharField(max_length=16)),
                ("network", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="teleconsultevent",
            name="teleconsult_event_kind_check",
        ),
        migrations.AddField(
            model_name="teleconsultroom",
            name="provider",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="teleconsultroom",
            name="provider_environment",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddConstraint(
            model_name="teleconsultevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        (
                            "created",
                            "joined",
                            "join_denied",
                            "started",
                            "ended",
                            "failed",
                            "reconnected",
                            "audio_only",
                            "video_restored",
                            "removed",
                        ),
                    )
                ),
                name="teleconsult_event_kind_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="teleconsultroom",
            constraint=models.UniqueConstraint(
                fields=("room_name",), name="teleconsult_room_name_uniq"
            ),
        ),
        migrations.AddField(
            model_name="teleconsultdevicecheck",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="identity.organization"
            ),
        ),
        migrations.AddField(
            model_name="teleconsultdevicecheck",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="device_checks",
                to="teleconsult.teleconsultsession",
            ),
        ),
        migrations.AddConstraint(
            model_name="teleconsultdevicecheck",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ("physician", "patient"))),
                name="teleconsult_device_role_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="teleconsultdevicecheck",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "camera__in",
                        (
                            "ok",
                            "denied",
                            "missing",
                            "busy",
                            "unsupported",
                            "error",
                            "not_checked",
                        ),
                    ),
                    (
                        "microphone__in",
                        (
                            "ok",
                            "denied",
                            "missing",
                            "busy",
                            "unsupported",
                            "error",
                            "not_checked",
                        ),
                    ),
                    ("network__in", ("good", "degraded", "offline", "not_checked")),
                    (
                        "speaker__in",
                        (
                            "ok",
                            "denied",
                            "missing",
                            "busy",
                            "unsupported",
                            "error",
                            "not_checked",
                        ),
                    ),
                ),
                name="teleconsult_device_result_check",
            ),
        ),
        migrations.RunPython(_seed, migrations.RunPython.noop),
        migrations.RunSQL(SQL, REVERSE_SQL),
    ]
