# Generated by hand for the task-43 protected-field integration on 2026-09-22
"""Encrypt the published consent text body.

``consent_consenttext.text`` becomes a tenant-envelope ``bytea`` column;
``digest`` stays the plaintext SHA-256 the acceptance token binds to. The
consent guard can no longer hash ciphertext, so it enforces presence, the
ciphertext size bound and the digest format; the service computes the digest
over the exact plaintext it encrypts, preserving the published-text binding.
The migration is irreversible because rollback must never reactivate
plaintext storage.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

from django.db import migrations

import apps.tenancy.fields
from apps.tenancy.migrations._protected_migration import (
    drop_legacy_sql,
    encrypt_backfill,
    irreversible,
    rename_to_legacy_sql,
    require_backfill_complete,
)

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


def _encode_text(value: object) -> bytes | None:
    if value is None or value == "":
        return None
    return str(value).encode("utf-8")


_PLANS = (
    (
        "text",
        "consent.consenttext.text",
        ("text_legacy",),
        (),
        lambda row: _encode_text(row["text_legacy"]),
        None,
    ),
)

_SCHEMA_SQL = (
    rename_to_legacy_sql("consent_consenttext", "text")
    + """
ALTER TABLE clinic_app.consent_consenttext
    ADD COLUMN IF NOT EXISTS text pg_catalog.bytea;
"""
)

_GUARD_SQL = """
SET LOCAL ROLE clinic_resolver;
CREATE OR REPLACE FUNCTION clinic_app.consent_guard()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp AS $f$
DECLARE s RECORD; t RECORD; a RECORD; last_version integer;
BEGIN
 IF TG_TABLE_NAME='consent_consenttext' THEN
   IF NOT clinic_app.questionnaire_staff(NEW.clinic_id,ARRAY['owner','clinic_admin'])
      OR NEW.published_by_id IS DISTINCT FROM
        NULLIF(current_setting('app.current_user_id',true),'')::uuid
      OR NOT EXISTS (SELECT 1 FROM clinic_app.identity_clinic c
        WHERE c.id=NEW.clinic_id AND c.organization_id=NEW.organization_id)
      OR NEW.text IS NULL OR pg_catalog.octet_length(NEW.text)>40000
      OR NEW.digest !~ '^[0-9a-f]{64}$'
   THEN RAISE EXCEPTION 'invalid consent publication' USING ERRCODE='23514'; END IF;
   PERFORM pg_advisory_xact_lock(hashtextextended(
     'consent:'||NEW.clinic_id||':'||NEW.purpose,0));
   SELECT coalesce(max(version),0) INTO last_version
     FROM clinic_app.consent_consenttext
     WHERE clinic_id=NEW.clinic_id AND purpose=NEW.purpose;
   IF NEW.version <> last_version+1 THEN
     RAISE EXCEPTION 'stale consent publication' USING ERRCODE='23514'; END IF;
   NEW.created_at := statement_timestamp();
   RETURN NEW;
 END IF;
 SELECT * INTO s FROM clinic_app.consent_session();
 IF s.session_id IS NULL OR NEW.patient_session_id IS DISTINCT FROM s.session_id
 OR NEW.organization_id IS DISTINCT FROM s.organization_id
 OR NEW.clinic_id IS DISTINCT FROM s.clinic_id THEN
   RAISE EXCEPTION 'patient consent authority required' USING ERRCODE='42501'; END IF;
 IF TG_TABLE_NAME='consent_consentacceptance' THEN
   SELECT * INTO t FROM clinic_app.consent_consenttext WHERE id=NEW.text_id;
   IF t.id IS NULL OR t.clinic_id IS DISTINCT FROM s.clinic_id
      OR NEW.patient_id IS DISTINCT FROM s.patient_id
      OR NEW.enrollment_id IS DISTINCT FROM s.enrollment_id THEN
     RAISE EXCEPTION 'invalid consent binding' USING ERRCODE='23514'; END IF;
   PERFORM pg_advisory_xact_lock(hashtextextended(
     'consent:'||t.clinic_id||':'||t.purpose,0));
   IF EXISTS (SELECT 1 FROM clinic_app.consent_consenttext newer
     WHERE newer.clinic_id=t.clinic_id AND newer.purpose=t.purpose
       AND newer.version>t.version) THEN
     RAISE EXCEPTION 'stale consent text' USING ERRCODE='23514'; END IF;
   NEW.accepted_at := statement_timestamp();
 ELSE
   SELECT * INTO a FROM clinic_app.consent_consentacceptance WHERE id=NEW.acceptance_id;
   IF a.id IS NULL OR a.enrollment_id IS DISTINCT FROM s.enrollment_id
      OR a.patient_id IS DISTINCT FROM s.patient_id
      OR a.clinic_id IS DISTINCT FROM s.clinic_id THEN
     RAISE EXCEPTION 'invalid revocation binding' USING ERRCODE='23514'; END IF;
   NEW.revoked_at := statement_timestamp();
 END IF;
 RETURN NEW;
END
$f$;
RESET ROLE;
"""

_DROP_SQL = (
    drop_legacy_sql("consent_consenttext", "text", required=True)
    + """
ALTER TABLE clinic_app.consent_consenttext
    ALTER COLUMN text SET NOT NULL;
"""
)


class Migration(migrations.Migration):
    """Convert the consent text body to a tenant envelope."""

    atomic = False
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("consent", "0002_consent_policy"),
        ("tenancy", "0004_protected_fields"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_SCHEMA_SQL, reverse_sql=None),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name="consenttext",
                    old_name="text",
                    new_name="text_legacy",
                ),
                migrations.AddField(
                    model_name="consenttext",
                    name="text",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="consent.consenttext.text", null=True
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            code=encrypt_backfill(
                table="consent_consenttext", pk_column="id", plans=_PLANS
            ),
            reverse_code=irreversible,
        ),
        migrations.RunSQL(sql=_GUARD_SQL, reverse_sql=None),
        migrations.RunPython(
            code=require_backfill_complete(table="consent_consenttext", plans=_PLANS),
            reverse_code=irreversible,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_DROP_SQL, reverse_sql=None),
            ],
            state_operations=[
                migrations.RemoveField(model_name="consenttext", name="text_legacy"),
                migrations.AlterField(
                    model_name="consenttext",
                    name="text",
                    field=apps.tenancy.fields.EncryptedTextField(
                        purpose="consent.consenttext.text"
                    ),
                ),
            ],
        ),
    ]
