# Generated by Django 5.2.17 on 2026-09-25 08:06, hand-edited for posture SQL
"""Purpose taxonomy, notices, refusals, participant and AI-use records.

Widens the ``consent_text_scope_check`` purpose vocabulary, adds the
immutable notice/refusal/acknowledgment/disclosure tables and installs
their FORCE-RLS policies, grants and binding triggers.
"""

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.operations.base import Operation

import apps.tenancy.fields

from ._taxonomy_sql import REVERSE_SQL, SQL


class Migration(migrations.Migration):
    """Add the consent taxonomy surface; every table keeps immutable history."""

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("consent", "0003_protected_fields"),
        ("ehr", "0009_protected_fields"),
        ("identity", "0013_permission_bundles"),
        ("intake", "0011_protected_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.CreateModel(
            name="AIUseDisclosure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("informed", models.BooleanField()),
                ("refused", models.BooleanField()),
                ("recorded_at", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NoticeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("care_processing", "Care data processing"),
                            ("consultation_recording", "Consultation recording"),
                            ("ai_use", "Use of AI in care"),
                            ("teleconsultation", "Teleconsultation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("language", models.CharField(default="pt-BR", max_length=16)),
                (
                    "text",
                    apps.tenancy.fields.EncryptedTextField(
                        purpose="consent.noticeversion.text"
                    ),
                ),
                ("digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParticipantAcknowledgment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "participant_kind",
                    models.CharField(
                        choices=[
                            ("caregiver", "Caregiver"),
                            ("companion", "Companion"),
                            ("interpreter", "Interpreter"),
                        ],
                        max_length=16,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RefusalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "authority",
                    models.CharField(default="patient_explicit_action", max_length=32),
                ),
                ("refused_at", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="consenttext",
            name="consent_text_scope_check",
        ),
        migrations.AlterField(
            model_name="consenttext",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("teleconsultation", "Teleconsultation"),
                    ("consultation_recording", "Consultation recording"),
                    ("ai_assistance", "AI assistance"),
                    ("transactional_messaging", "Transactional messaging"),
                    ("marketing", "Marketing"),
                    ("research_model_improvement", "Research and model improvement"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="consenttext",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("language", "pt-BR"),
                    (
                        "purpose__in",
                        [
                            "teleconsultation",
                            "consultation_recording",
                            "ai_assistance",
                            "transactional_messaging",
                            "marketing",
                            "research_model_improvement",
                        ],
                    ),
                    ("version__gte", 1),
                ),
                name="consent_text_scope_check",
            ),
        ),
        migrations.AddField(
            model_name="aiusedisclosure",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="identity.clinic"
            ),
        ),
        migrations.AddField(
            model_name="aiusedisclosure",
            name="encounter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="ehr.encounter"
            ),
        ),
        migrations.AddField(
            model_name="aiusedisclosure",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="identity.organization",
            ),
        ),
        migrations.AddField(
            model_name="aiusedisclosure",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="intake.patient"
            ),
        ),
        migrations.AddField(
            model_name="aiusedisclosure",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="noticeversion",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="identity.clinic"
            ),
        ),
        migrations.AddField(
            model_name="noticeversion",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="identity.organization",
            ),
        ),
        migrations.AddField(
            model_name="noticeversion",
            name="published_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participantacknowledgment",
            name="acknowledged_by_clinician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participantacknowledgment",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="identity.clinic"
            ),
        ),
        migrations.AddField(
            model_name="participantacknowledgment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="identity.organization",
            ),
        ),
        migrations.AddField(
            model_name="participantacknowledgment",
            name="session",
            field=models.ForeignKey(
                help_text="The clinical session (encounter) the voice participates in.",
                on_delete=django.db.models.deletion.PROTECT,
                to="ehr.encounter",
            ),
        ),
        migrations.AddField(
            model_name="refusalrecord",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="identity.clinic"
            ),
        ),
        migrations.AddField(
            model_name="refusalrecord",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="intake.patientclinicenrollment",
            ),
        ),
        migrations.AddField(
            model_name="refusalrecord",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="identity.organization",
            ),
        ),
        migrations.AddField(
            model_name="refusalrecord",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="intake.patient"
            ),
        ),
        migrations.AddField(
            model_name="refusalrecord",
            name="patient_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="intake.patientsession",
            ),
        ),
        migrations.AddField(
            model_name="refusalrecord",
            name="text",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="consent.consenttext",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiusedisclosure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("refused", False), ("informed", True), _connector="OR"
                ),
                name="consent_ai_disclosure_coherent_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="noticeversion",
            constraint=models.UniqueConstraint(
                fields=("clinic", "topic", "version"),
                name="consent_notice_version_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="noticeversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("language", "pt-BR"),
                    (
                        "topic__in",
                        [
                            "care_processing",
                            "consultation_recording",
                            "ai_use",
                            "teleconsultation",
                        ],
                    ),
                    ("version__gte", 1),
                ),
                name="consent_notice_scope_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="participantacknowledgment",
            constraint=models.UniqueConstraint(
                fields=("session", "participant_kind"),
                name="consent_participant_ack_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="participantacknowledgment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "participant_kind__in",
                        ["caregiver", "companion", "interpreter"],
                    )
                ),
                name="consent_participant_kind_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="refusalrecord",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "text"), name="consent_refusal_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="refusalrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("authority", "patient_explicit_action")),
                name="consent_refusal_authority_check",
            ),
        ),
        migrations.RunSQL(SQL, REVERSE_SQL),
    ]
