# Generated by hand for the task-43 protected-field integration on 2026-09-22
"""Return the encrypted SOAP envelope from the patient releases resolver.

``ehr_clinicaldocumentversion`` no longer stores plaintext SOAP columns, so
``retention_patient_releases`` now returns the single ``content`` envelope;
the service decrypts it under the live patient session through the
protected boundary. The resolver predicate is unchanged.
"""

from typing import ClassVar

from django.db import migrations
from django.db.migrations.operations.base import Operation

SQL = """
SET LOCAL ROLE clinic_resolver;
DROP FUNCTION clinic_app.retention_patient_releases();
CREATE FUNCTION clinic_app.retention_patient_releases()
RETURNS TABLE(release_id pg_catalog.uuid, version_id pg_catalog.uuid,
              document_id pg_catalog.uuid, encounter_id pg_catalog.uuid,
              version_number pg_catalog.int4,
              state pg_catalog.text, content_digest pg_catalog.text,
              finalized_at pg_catalog.timestamptz,
              amendment_of_version pg_catalog.int4,
              author_label pg_catalog.text,
              content pg_catalog.bytea,
              released_at pg_catalog.timestamptz)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, clinic_app, pg_temp AS $f$
 SELECT r.id, v.id, d.id, e.id, v.version, v.state::pg_catalog.text,
   v.content_digest::pg_catalog.text,
   v.finalized_at, base.version, u.username::pg_catalog.text,
   v.content, r.created_at
   FROM clinic_app.retention_recordrelease r
   JOIN clinic_app.ehr_clinicaldocumentversion v ON v.id = r.version_id
   JOIN clinic_app.ehr_clinicaldocument d ON d.id = v.document_id
   JOIN clinic_app.ehr_encounter e ON e.id = d.encounter_id
   JOIN clinic_app.identity_user u ON u.id = v.author_id
   LEFT JOIN clinic_app.ehr_clinicaldocumentversion base
     ON base.id = v.amendment_of_id
   WHERE r.revoked_at IS NULL
   AND EXISTS (SELECT 1 FROM clinic_app.retention_records_session() s
     WHERE s.organization_id = r.organization_id
     AND s.clinic_id = r.clinic_id AND s.patient_id = r.patient_id)
   ORDER BY e.created_at, d.id, v.version
$f$;
REVOKE ALL ON FUNCTION clinic_app.retention_patient_releases()
 FROM PUBLIC, clinic_app;
-- Recreating the function drops its grants; clinic_owner needs EXECUTE back
-- because retention_record_viewed runs as the owner and uses this resolver
-- as its release authority.
GRANT EXECUTE ON FUNCTION clinic_app.retention_patient_releases()
 TO clinic_app, clinic_owner;
RESET ROLE;
"""


class Migration(migrations.Migration):
    """Return the content envelope from the patient releases resolver."""

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("ehr", "0009_protected_fields"),
        ("retention", "0002_retention_policy"),
        ("tenancy", "0004_protected_fields"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.RunSQL(sql=SQL, reverse_sql=None),
    ]
