# Generated by Django 5.2.16 on 2026-07-13
"""Create the native PostgreSQL audit event ledger relation."""

from typing import ClassVar

from django.db import migrations, models
from django.db.migrations.operations.base import Operation

import apps.audit.models

TABLE_HARDENING_SQL = """
ALTER TABLE clinic_app.audit_event
    ALTER COLUMN seq SET GENERATED ALWAYS;

ALTER TABLE clinic_app.audit_event
    ADD CONSTRAINT audit_event_prev_hash_len_ck
        CHECK (pg_catalog.octet_length(prev_hash) = 32),
    ADD CONSTRAINT audit_event_curr_hash_len_ck
        CHECK (pg_catalog.octet_length(curr_hash) = 32),
    ADD CONSTRAINT audit_event_payload_object_ck
        CHECK (pg_catalog.jsonb_typeof(payload) = 'object'),
    ADD CONSTRAINT audit_event_event_type_text_ck
        CHECK (pg_catalog.char_length(pg_catalog.btrim(event_type)) BETWEEN 1 AND 128),
    ADD CONSTRAINT audit_event_component_id_text_ck
        CHECK (
            pg_catalog.char_length(pg_catalog.btrim(component_id))
                BETWEEN 1 AND 255
        ),
    ADD CONSTRAINT audit_event_affected_pair_ck
        CHECK (
            (affected_record_type IS NULL AND affected_record_id IS NULL)
            OR
            (affected_record_type IS NOT NULL AND affected_record_id IS NOT NULL)
        ),
    ADD CONSTRAINT audit_event_affected_text_ck
        CHECK (
            affected_record_type IS NULL
            OR (
                pg_catalog.char_length(pg_catalog.btrim(affected_record_type))
                    BETWEEN 1 AND 128
                AND pg_catalog.char_length(pg_catalog.btrim(affected_record_id))
                    BETWEEN 1 AND 255
            )
        ),
    ADD CONSTRAINT audit_event_timestamp_finite_ck
        CHECK (pg_catalog.isfinite(occurred_at_utc)),
    ADD CONSTRAINT audit_event_component_ip_host_ck
        CHECK (
            component_ip IS NULL
            OR (
                pg_catalog.family(component_ip) = 4
                AND pg_catalog.masklen(component_ip) = 32
            )
            OR (
                pg_catalog.family(component_ip) = 6
                AND pg_catalog.masklen(component_ip) = 128
            )
        ),
    ADD CONSTRAINT audit_event_actor_scope_ck
        CHECK (
            organization_id = '00000000-0000-0000-0000-000000000000'::pg_catalog.uuid
            OR actor_user_id IS NOT NULL
        );

REVOKE ALL ON TABLE clinic_app.audit_event
    FROM PUBLIC, clinic_app, clinic_resolver;
REVOKE ALL ON SEQUENCE clinic_app.audit_event_seq_seq
    FROM PUBLIC, clinic_app, clinic_resolver;
"""


class Migration(migrations.Migration):
    """Create and harden the append-only ledger base relation."""

    initial = True

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("identity", "0002_userclinicrole_org_clinic_fk"),
    ]

    operations: ClassVar[list[Operation]] = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("seq", models.BigAutoField(primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField()),
                ("actor_user_id", models.UUIDField(blank=True, null=True)),
                ("event_type", models.CharField(max_length=128)),
                ("component_id", models.CharField(max_length=255)),
                (
                    "component_ip",
                    apps.audit.models.InetAddressField(blank=True, null=True),
                ),
                (
                    "affected_record_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "affected_record_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("occurred_at_utc", models.DateTimeField()),
                ("payload", models.JSONField()),
                ("prev_hash", models.BinaryField(max_length=32)),
                ("curr_hash", models.BinaryField(max_length=32, unique=True)),
            ],
            options={
                "db_table": "audit_event",
                "indexes": [
                    models.Index(
                        fields=["organization_id", "-seq"],
                        include=("curr_hash",),
                        name="audit_event_org_seq_hash_idx",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql=TABLE_HARDENING_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
